bpmn-io/diagram-js

lib/features/overlays/Overlays.js
test/spec/features/overlays/OverlaysSpec.js

fix(overlays): respect min/max zoom level when overlay is added

---

lib/features/modeling/cmd/LayoutConnectionHandler.js
test/spec/features/modeling/LayoutConnectionSpec.js

chore(modeling): don't move connections to front during layout

---

lib/features/modeling/Modeling.js
lib/features/modeling/cmd/CreateConnectionHandler.js
test/spec/features/modeling/CreateConnectionSpec.js
test/spec/features/modeling/CreateShapeSpec.js
test/spec/features/ordering/OrderingProviderSpec.js

216 parent index

---

lib/features/auto-resize/AutoResize.js
test/spec/features/auto-resize/AutoResizeSpec.js

* autoResize can either be boolean or array of elements to consider when resizing
Related to bpmn-io/bpmn-js#483

Allow specifying elements when auto-resizing after move

---

lib/layout/ManhattanLayout.js
test/spec/layout/ManhattanLayoutSpec.js

* add t|r|b|l as configuration options when laying out a connection

Add more configuration options to manhattan layout algorithm

---

README.md

* remove project since it's not online at the moment

chore(README): update

---

karma.conf.js
package-lock.json
package.json

* up to 30% faster test execution over spec reporter

test(project): use built-in progress reporter

---

lib/core/EventBus.js
test/spec/core/EventBusSpec.js

chore(core/EventBus): implement as double linked list

---

CHANGELOG.md
package-lock.json
package.json
test/spec/features/context-pad/ContextPadSpec.js
test/spec/features/dragging/DraggingSpec.js
test/spec/features/overlays/OverlaysSpec.js
test/spec/features/popup-menu/PopupMenuSpec.js

Related to https://github.com/bpmn-io/bpmn-js/issues/879.

Workaround MS Edge blowing up when setting SVG transform

---

lib/features/modeling/cmd/ReconnectConnectionHandler.js
test/spec/features/bendpoints/BendpointsMoveSpec.js
test/spec/features/modeling/ReconnectConnectionSpec.js

Required by https://github.com/bpmn-io/bpmn-js/issues/940

Do the layouting after reconnection

---

lib/layout/ManhattanLayout.js

This PR is aimed to make code more readable.

chore(ManhattanLayout): refactor #repairConnection

---

lib/features/modeling/cmd/ReconnectConnectionHandler.js
test/spec/features/modeling/ReconnectConnectionSpec.js

This PR corrects layouting behavior on reconnection.

fix(modeling/reconnect): correctly layout endpoints

---

lib/features/auto-resize/AutoResize.js
lib/features/grid-snapping/GridSnapping.js
lib/features/grid-snapping/behavior/ResizeBehavior.js
lib/features/grid-snapping/behavior/SpaceToolBehavior.js
lib/features/grid-snapping/behavior/index.js
lib/features/grid-snapping/index.js
lib/features/modeling/Modeling.js
lib/features/move/Move.js
lib/navigation/zoomscroll/ZoomScroll.js
lib/navigation/zoomscroll/ZoomUtil.js
test/spec/features/auto-resize/AutoResizeSpec.js
test/spec/features/grid-snapping/GridSnappingSpec.js
test/spec/features/grid-snapping/behavior/ResizeBehaviorSpec.js
test/spec/features/grid-snapping/behavior/SpaceToolBehaviorSpec.js
test/spec/features/move/MoveSpec.js

* allow snapping create/move with offset
* integrate auto resize
* integrate space tool
Related to camunda/camunda-modeler#1344
Related to camunda/camunda-modeler#1348
Related to camunda/camunda-modeler#1349

1344 Integrate Grid Snapping - Part 1

---

lib/features/grid-snapping/Grid.js
lib/features/grid-snapping/GridSnapping.js
lib/features/grid-snapping/behavior/PasteBehavior.js
lib/features/grid-snapping/behavior/index.js
test/spec/features/grid-snapping/behavior/PasteBehaviorSpec.js
test/spec/features/grid-snapping/behavior/ResizeBehaviorSpec.js

Integrate Grid Snapping with Copy/Paste Feature

---

assets/diagram-js.css
lib/features/move/MovePreview.js
lib/features/preview-support/PreviewSupport.js
test/spec/features/move/MovePreviewSpec.js
test/spec/features/move/renderer/MarkerRenderer.js
test/spec/features/move/renderer/index.js

Related to https://github.com/bpmn-io/bpmn-js/issues/1013.

Clone <marker> Elements Instead of Removing Them

---

lib/features/move/MovePreview.js
test/spec/features/move/MovePreviewSpec.js

fix(move-preview): cleanup preview after move

---

lib/features/create/Create.js

* follow-up of the 22-05-19 hour of code
* cf. https://github.com/bpmn-io/hour-of-code/blob/master/snippets/Create_canCreate.md

chore(create): merge multiple if statements

---

lib/features/connection-preview/ConnectionPreview.js

Required by https://github.com/bpmn-io/bpmn-js/pull/1035.

Do Not Attempt Preview If No Target

---

lib/features/bendpoints/BendpointMove.js
test/spec/features/bendpoints/BendpointsMoveSpec.js

A small improvement which came up in a discussion with @nikku

feat(bendpoints): disable dragging if not allowed from start

---

lib/features/bendpoints/BendpointSnapping.js
test/spec/features/bendpoints/BendpointsMoveSpec.js
test/spec/features/bendpoints/ConnectionSegmentMoveSpec.js

fix(bendpoints): mark events as snapped

---

lib/features/hand-tool/HandTool.js
lib/features/hand-tool/index.js
lib/features/keyboard/Keyboard.js
test/spec/features/hand-tool/HandToolSpec.js
test/spec/features/keyboard/KeyboardSpec.js
test/util/KeyEvents.js

Related to camunda/camunda-modeler#321

feat(hand-tool): activate on space

---

lib/features/grid-snapping/visuals/Grid.js
test/spec/features/grid-snapping/visuals/GridSpec.js

Center Grid around Viewbox on Viewbox Changed

---

lib/features/space-tool/SpaceToolPreview.js
test/spec/features/space-tool/SpaceToolSpec.js

Related to bpmn-io/bpmn-js#1105

fix(space-tool-preview): correctly update resize previews

---

lib/features/bendpoints/BendpointMovePreview.js
package-lock.json
test/spec/features/bendpoints/BendpointsMoveSpec.js

Do not show connect allowed markers on bendpoint move

---

lib/features/bendpoints/BendpointMove.js
lib/features/bendpoints/BendpointMovePreview.js
lib/features/bendpoints/ConnectionSegmentMove.js
lib/features/connect/ConnectPreview.js

This cleans up some internals in the `bendpoints` and `connect` departments.
* removes duplication
* makes code easier to understand
* makes code easier to read

Bendpoints improvements

---

lib/features/copy-paste/CopyPaste.js
lib/features/grid-snapping/GridSnapping.js
test/spec/features/grid-snapping/GridSnappingSpec.js

* handle creating multiple elements
* cache snap constraints and offset
Related to https://github.com/bpmn-io/bpmn-js/issues/1150.

Grid Snapping Can Handle Creating Multiple Elements

---

CHANGELOG.md
lib/features/grid-snapping/GridSnapping.js
test/spec/features/grid-snapping/GridSnappingSpec.js

Related to bpmn-io/bpmn-js#1158

1158 fix create grid snapping

---

lib/features/create/Create.js
test/spec/features/create/CreateSpec.js

Related to bpmn-io/bpmn-js#1144

fix(create): do not allow create if no hover

---

lib/layout/ManhattanLayout.js
lib/util/Geometry.js
test/spec/layout/ManhattanLayoutSpec.js

Related to bpmn-io/bpmn-js#1121

fix(manhattan-layout): always relayout loops

---

lib/features/create/CreatePreview.js
test/spec/features/create/CreatePreviewSpec.js

Related to camunda/camunda-modeler#1481

fix(create): only update preview if hover

---

lib/features/keyboard-move-selection/KeyboardMoveSelection.js
test/spec/features/keyboard-move-selection/KeyboardMoveSelectionSpec.js
test/spec/features/keyboard-move-selection/rules/KeyboardMoveRules.js
test/spec/features/keyboard-move-selection/rules/index.js

Required by https://github.com/bpmn-io/bpmn-js/pull/1185
Related to bpmn-io/bpmn-js#943

fix(keyboard-move-selection): integrate rules

---

lib/features/attach-support/AttachSupport.js
test/spec/features/attach-support/AttachSupportSpec.js

* allow detaching multiple shapes
Required by https://github.com/bpmn-io/bpmn-js/pull/1203.

Allow Detaching Multiple Shapes

---

lib/features/modeling/cmd/ToggleShapeCollapseHandler.js
test/spec/features/modeling/ToggleShapeCollapseSpec.js

Required by https://github.com/camunda/camunda-modeler/issues/1328

Hide elements recursively

---

CHANGELOG.md

This PR updates changelog to include upcoming patch release.

chore(CHANGELOG): update to v5.1.1

---

lib/features/modeling/cmd/ReplaceShapeHandler.js
test/spec/features/auto-resize/AutoResizeSpec.js
test/spec/features/modeling/LayoutConnectionSpec.js
test/spec/features/modeling/ReplaceShapeSpec.js

Related to bpmn-io/bpmn-js#1231

fix(replace): pass hints when moving children on replace

---

test/spec/features/bendpoints/BendpointsMoveSpec.js

Related to https://github.com/bpmn-io/diagram-js/commit/0ad106622bba40e80fe2a5ac858a92dbf9488f36#diff-aaa55ad67fc67521dcfbfdf3b6cc259aR481.

chore(bendpoints): actually test

---

assets/diagram-js.css
lib/features/grid-snapping/GridSnapping.js
lib/features/resize/Resize.js
lib/features/resize/ResizeHandles.js
lib/features/resize/ResizeUtil.js
lib/features/snapping/ResizeSnapping.js
lib/util/SvgTransformUtil.js
test/spec/features/resize/ResizeSpec.js
test/spec/snapping/ResizeSnappingSpec.js

feat(resize): resize horizontally and vertically

---

CHANGELOG.md
lib/features/create/CreatePreview.js
lib/features/selection/SelectionBehavior.js
test/spec/features/create/CreatePreviewSpec.js
test/spec/features/create/CreateSpec.js

A follow up to #441 that properly creates collapsed element on the canvas.

Hidden create

---

lib/features/space-tool/SpaceTool.js
test/spec/features/space-tool/SpaceToolSpec.js
test/spec/features/space-tool/rules/SpaceRules.js

fix(space-tool): do not fail on falsy values

---

lib/features/selection/SelectionBehavior.js
test/spec/features/selection/SelectionSpec.js
test/spec/features/selection/rules/ConnectRules.js
test/spec/features/selection/rules/index.js

fix(selection): select connect interaction target on connect

---

lib/features/modeling/cmd/AppendShapeHandler.js

fix(modeling): remove wrong argument from modeling API usage

---

lib/features/auto-place/AutoPlaceUtil.js
test/spec/features/auto-place/AutoPlaceSpec.js

* assume left-to-right and top-to-down modeling
*  weight => 0 means elements after will be considered
* weight < 0 means elements before will be considered

fix(auto-place): get connected distance based on weight

---

assets/diagram-js.css
lib/features/bendpoints/BendpointUtil.js
test/spec/features/bendpoints/BendpointsSpec.js

Align colors with Camunda Modeler

---

lib/features/keyboard/KeyboardBindings.js
test/spec/features/keyboard/RemoveSelectionSpec.js

feat(keyboard-bindings): add Backspace key for element removal

---

test/spec/features/move/MovePreviewSpec.js

__Which issue does this PR address?__
Closes #485
__Acceptance Criteria__

fix(test): relax tests and allow env-specific variation using url() css

---

lib/features/selection/SelectionBehavior.js
test/spec/features/selection/SelectionSpec.js

__Which issue does this PR address?__
Closes #471 

feat(selection): add to selection with SHIFT + click

---

.github/workflows/ci.yml

This aims to replace our Travis CI builds.

chore: add GitHub <ci> action

---

CHANGELOG.md

Updates the CHANGELOG to `v7.0.0`.

chore(CHANGELOG): update to v7.0.0

---

.github/workflows/CI.yml
lib/util/Mouse.js
test/spec/features/hand-tool/HandToolSpec.js
test/spec/features/selection/SelectionBehaviorSpec.js

* run CI on macOS and Windows
* set environment variables via step configuration
* set correct key modifier 
Read https://github.com/bpmn-io/diagram-js/issues/520#issuecomment-762327928 for more explanations.
__Which issue does this PR address?__
Closes #520
__Acceptance Criteria__

Fixup macos test suite

---

lib/core/EventBus.js
test/spec/core/EventBusSpec.js

Closes https://github.com/bpmn-io/diagram-js/issues/524

Once only once

---

lib/features/bendpoints/BendpointMove.js
test/spec/features/bendpoints/BendpointsMoveSpec.js

Related to bpmn-io/bpmn-js#1387.

fix(bendpoint-move): always allow moving bendpoint

---

assets/diagram-js.css
lib/features/resize/ResizeHandles.js
test/spec/features/resize/ResizeSpec.js

* shows resize handles on selection _and_ hover which is consistent with outline behavior
* increases size of handles which is consistent with size of bendpoint draggers

Show Resize Handles on Hover

---

assets/diagram-js.css
lib/features/resize/ResizeHandles.js
test/spec/features/resize/ResizeSpec.js

Found a breaking issue: https://github.com/bpmn-io/diagram-js/pull/543#issuecomment-829146530.
Reverts bpmn-io/diagram-js#543

Revert "Show Resize Handles on Hover"

---

lib/core/EventBus.js
test/spec/features/dragging/DraggingSpec.js

* add test to verify dragging errors can be intercepted via eventBus.
* log eventBus uncaught errors on same line with message.

Verify dragging error handling + event bus integration

---

lib/core/Canvas.js
lib/core/ElementRegistry.js
lib/features/connection-preview/ConnectionPreview.js
lib/features/create/CreatePreview.js
lib/features/lasso-tool/LassoTool.js
lib/features/move/MovePreview.js
lib/features/overlays/Overlays.js
lib/features/planes/PlanesBehavior.js
lib/features/planes/index.js
lib/features/resize/ResizePreview.js
lib/features/selection/Selection.js
lib/features/space-tool/SpaceToolPreview.js
test/spec/core/CanvasSpec.js
test/spec/core/ElementRegistrySpec.js
test/spec/features/overlays/OverlaysSpec.js
test/spec/features/planes/PlanesBehaviorSpec.js
test/spec/features/resize/ResizeSpec.js
test/spec/features/selection/SelectionBehaviorSpec.js
test/spec/features/selection/SelectionSpec.js

related to #560
for manual testing, you can use the bpmn-js prototype on this branch: https://github.com/bpmn-io/bpmn-js/tree/sub-process-prototype
----
Closes #561

Support multiple planes for rendering elements

---

lib/core/Canvas.js
test/spec/core/CanvasSpec.js

Related to https://github.com/bpmn-io/bpmn-js/issues/1520

fix(plane): render content behind resize handles

---

lib/core/Canvas.js
test/spec/core/CanvasSpec.js

fix(canvas): allow IDs for #scrollToElement

---

lib/core/Canvas.js
test/spec/core/CanvasSpec.js

fix(canvas): ensure plane is available before switch

---

lib/core/Canvas.js
test/spec/core/CanvasSpec.js

small improvement for the Canvas API

feat(core/canvas): return removed element

---

CHANGELOG.md

Prepare 8.0.1 release

---

CHANGELOG.md

* I missed a commit when updating the CHANGELOG

chore(CHANGELOG): correct 8.0.1 changelog

---

lib/features/copy-paste/CopyPaste.js
lib/features/create/Create.js
lib/features/modeling/cmd/CreateElementsHandler.js
test/spec/features/copy-paste/CopyPasteSpec.js
test/spec/features/create/CreateSpec.js

This PR allows us to hook into tree creation when copying collapsed processes.
See https://github.com/bpmn-io/bpmn-js/pull/1563 for implementation in bpmn-js

feat(copy-paste): allow hooking into tree creation

---

lib/Diagram.js
package-lock.json
package.json

Replace our bootstrapping code with what is new in [didi@8](https://github.com/nikku/didi).

Upgrade to `didi@8`

---

lib/layout/LayoutUtil.js
test/spec/features/modeling/CreateConnectionSpec.js

try it out:
```
npx @bpmn-io/sr bpmn-io/bpmn-js#connection-association -l bpmn-io/diagram-js#connection-association
```

feat: allow adding connections to connections

---

CHANGELOG.md

chore(CHANGELOG): update to v8.4.0

---

lib/features/bendpoints/BendpointSnapping.js
lib/features/bendpoints/BendpointUtil.js
lib/features/bendpoints/GeometricUtil.js
test/spec/features/bendpoints/BendpointsMoveSpec.js
test/spec/features/bendpoints/GeometricUtilSpec.js

related to https://github.com/bpmn-io/bpmn-js/pull/1661

feat(snapping): snap bendpoints on connection path

---

CHANGELOG.md

Requires https://github.com/bpmn-io/diagram-js/pull/654

chore(CHANGELOG): update to v8.6.0

---

lib/features/align-elements/AlignElements.js
lib/features/distribute-elements/DistributeElements.js
test/spec/features/align-elements/AlignElementsSpec.js
test/spec/features/align-elements/rules/TestRules.js
test/spec/features/align-elements/rules/index.js
test/spec/features/distribute-elements/DistributeElementsSpec.js
test/spec/features/distribute-elements/rules/TestRules.js
test/spec/features/distribute-elements/rules/index.js

Use rules for alignment and distribution

---

lib/features/keyboard/KeyboardBindings.js
lib/features/keyboard/KeyboardUtil.js
test/spec/features/keyboard/CopySpec.js
test/spec/features/keyboard/PasteSpec.js
test/spec/features/keyboard/RedoSpec.js
test/spec/features/keyboard/UndoSpec.js

Backports https://github.com/bpmn-io/diagram-js/pull/665 to 8.x.

feat(keyboard): make function detection available via explicit utilities

---

.github/workflows/CI.yml
test/spec/features/hand-tool/HandToolSpec.js
test/spec/features/popup-menu/PopupMenuSpec.js

Closes https://github.com/bpmn-io/diagram-js/issues/672

Correct CI failures

---

lib/features/popup-menu/PopupMenuProvider.js

docs: update popup menu provider example

---

.github/workflows/CI.yml

Update to codecov@3 + pin to ubuntu@20 (shipping with firefox).

Bump codecov action@3

---

lib/core/ElementRegistry.js

fix: some function's comment error

---

lib/features/popup-menu/PopupMenuComponent.js
test/spec/features/popup-menu/PopupMenuComponentSpec.js

Related to https://github.com/bpmn-io/bpmn-js/pull/1776#discussion_r1025284209

feat(popup-menu): make search false by default

---

lib/features/popup-menu/PopupMenu.js
lib/features/popup-menu/PopupMenuComponent.js
lib/features/popup-menu/PopupMenuItem.js
lib/features/popup-menu/PopupMenuList.js
test/spec/features/popup-menu/PopupMenuComponentSpec.js

Digging into https://github.com/bpmn-io/diagram-js/pull/710#issuecomment-1324793821 I found a couple of additional "quirks". All shall be fixed with this PR.

Popup menu header selection

---

CHANGELOG.md

chore(CHANGELOG): update to v11.1.0

---

lib/features/popup-menu/PopupMenu.js

Related to [forum post](https://forum.bpmn.io/t/ho-to-delete-entries-from-replace-menu-for-connections/8384).

docs(popup-menu): describe middleware provider registration

---

README.md

add archimate-js link in external libraries list

---

CHANGELOG.md

chore(CHANGELOG): update to v11.5.0

---

CHANGELOG.md
lib/features/popup-menu/PopupMenuComponent.js
lib/features/popup-menu/PopupMenuItem.js
test/spec/features/popup-menu/PopupMenuComponentSpec.js

Ensure icons are not read out by screen readers.
Closes #736

fix(popup-menu): make icons decoration

---

lib/features/modeling/cmd/AlignElementsHandler.js
test/spec/features/align-elements/AlignElementsSpec.js

fix: align with `alignment[type]=0`

---

CHANGELOG.md

chore(CHANGELOG): update to 11.6.0

---

lib/util/EscapeUtil.js

style: remove trailing whitespace

---

CHANGELOG.md

* `FEAT`: add TypeScript declarations for core components ([#732](https://github.com/bpmn-io/diagram-js/pull/732))
* `DEPS`: update to `didi@9.0.2`

chore(CHANGELOG): update to v11.10.0

---

lib/model/index.d.ts
lib/util/Types.js

See https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation.
---
Required by https://github.com/bpmn-io/bpmn-js/pull/1866

Adjust Type Declarations to Allow Augmentation

---

README.md

added a link to the chor-js demo

---

CHANGELOG.md

chore(CHANGELOG): update to v11.12.0

---

test/spec/features/popup-menu/PopupMenuComponentSpec.js

Attempts to fix our long shaky popup menu tests.

test: attempt to stabelize CI tests (MacOS)

---

lib/core/ElementFactory.spec.ts
lib/model/index.d.ts

fix(ElementFactory): change type declaration to accept any property

---

CHANGELOG.md

chore(CHANGELOG): update to v11.13.1

---

CHANGELOG.md

chore(CHANGELOG): update to v12.0.0

---

lib/features/modeling/cmd/CreateElementsHandler.js
test/spec/features/create/CreateSpec.js

Related to https://github.com/bpmn-io/bpmn-js/issues/1895

fix(create): do not attach label

---

CHANGELOG.md

chore(CHANGELOG): update to v12.1.0

---

lib/features/popup-menu/PopupMenuItem.js
test/spec/features/popup-menu/PopupMenuSpec.js

Related to https://github.com/bpmn-io/bpmn-js/issues/1918

feat(popupMenu): allow to provide html for entries

---

CHANGELOG.md

chore(CHANGELOG): update to v12.2.0

---

CHANGELOG.md

chore(CHANGELOG): update to v12.3.0

---

.github/workflows/CI.yml

chore: target node v20

---

CHANGELOG.md

chore(CHANGELOG): update to v12.4.0

---

lib/features/space-tool/SpaceTool.js
test/spec/features/space-tool/SpaceToolSpec.js

Related to https://github.com/bpmn-io/bpmn-js/issues/1975

Make Space Tool Local by Default

---

CHANGELOG.md

chore(CHANGELOG): update to v12.5.0

---

CHANGELOG.md
package-lock.json

chore(CHANGELOG): update to v12.6.0

---

lib/features/outline/Outline.js
test/spec/features/outline/OutlineSpec.js

Closes https://github.com/bpmn-io/diagram-js/issues/822

fix(outline): prevent access of non-existing connection bounds

---

CHANGELOG.md

chore(CHANGELOG): update to v12.8.0

---

CHANGELOG.md

chore(CHANGELOG): update to v12.8.1

---

README.md

Update name and link for object-diagram-js (previously object diagram modeler).

Update name and link for object-diagram-js

---

README.md

Cf. https://github.com/bpmn-io/bpmn-js-properties-panel
Cf. https://github.com/bpmn-io/bpmn-moddle/blob/main/README.md#building-the-project
Cf. https://github.com/bpmn-io/bpmn-js/blob/main/README.md#build-and-run

docs: align hacking section with other libraries

---

lib/features/tool-manager/ToolManager.js
test/spec/features/tool-manager/ToolManagerSpec.js

closes #881
Reproduction instructions can be found in the linked ticket

fix(ToolManager): do not force-cancel dragging

---

lib/features/palette/PaletteProvider.spec.ts
lib/features/palette/PaletteProvider.ts

fix(types):  Palatte entry actions

---

lib/features/move/MovePreview.js

Reported via https://camunda.slack.com/archives/C032H77434N/p1714116810618819

fix: prevent obvious error in move preview

---

.github/workflows/CI.yml
.github/workflows/CODE_SCANNING.yml
.github/workflows/MERGE_MASTER_TO_DEVELOP.yml

Follows along our updated conventions to use `snake_case` for job names.

ci: adjust job names to `snake_case`

---

assets/diagram-js.css
lib/features/preview-support/PreviewSupport.js
test/spec/features/interaction-events/InteractionEventsSpec.js
test/spec/features/palette/PaletteSpec.js
test/spec/features/popup-menu/PopupMenuSpec.js

Applies some basic chors (clean ups) in the project.

Housekeeping

---

.github/workflows/MERGE_MASTER_TO_DEVELOP.yml

Related to https://github.com/bpmn-io/internal-docs/issues/1094
This migrates the slack integration to use the v2 API.

ci: migrate to slack action v2

---

lib/core/EventBus.js
package-lock.json
package.json

Update to typescript@5.7.3, visualizing the changes.
Tested this against bpmn-js, module changes are also test covered via [`Diagram.spec.ts`](https://github.com/bpmn-io/diagram-js/blob/develop/lib/Diagram.spec.ts). 

Bump typescript

---

lib/features/popup-menu/PopupMenuComponent.js
test/spec/features/popup-menu/PopupMenuSpec.js

Related to https://github.com/camunda/camunda-modeler/issues/4948
always select the first found element
https://github.com/user-attachments/assets/65b0f862-ef51-4b9b-9df9-a2471d8d28e3
Steps to try out:
```
npx @bpmn-io/sr "bpmn-io/bpmn-js" -l "bpmn-io/diagram-js#4948-focus-highest-rank-during-search"  -c 'npm start'
```

Always select first search entry

---

lib/features/search/search.js
test/spec/features/popup-menu/PopupMenu.example-entries.json
test/spec/features/popup-menu/PopupMenuSpec.js
test/spec/features/search/searchSpec.js

Related to https://github.com/camunda/camunda-modeler/issues/4853
This PR changes the search result sort algorithm too allow entering arrays as part of the search items. Main use case is to support the search via keywords. while preparing the entries keywords are added to the search array and can be found.

Support searching through arrays of values
