- lib/navigation/zoomscroll/ZoomScroll.js
This PR improves the zoomscroll functionality by normalizing the zoom factor. When the user zooms out and then zooms in again, the zoom level is the same as before. With the previous solution, the diagram would be slightly zoomed out.
> impr(zoomscroll): normalize zoom factor

- package.json
This upgrade is necessary to run the tests on Windows machines
> chore(dependencies): upgrade karma-browserify

- lib/features/overlays/Overlays.js
- test/spec/features/overlays/OverlaysSpec.js
Incorporate #228 with the addition of being able to configure scaling in a more fine grained manner.
Make auto-hiding of overlays optional, effectively closing #229.
Closing #229 is a breaking change and deserves a mention in blog posts or other places (where appropriate).
> Overlay rework

- lib/core/Canvas.js
- test/spec/core/CanvasSpec.js
Ensure we reset the cached viewbox on element changes
so that the next `viewbox()` call pick up the possibly
updated SVG bounding box.
Related to bpmn-io/bpmn-js#771
> fix(core/Canvas): reset cached viewbox on element changes

- package.json
The new `sideEffects: false` declaration in the `package.json` is not quite correct. The CSS files, by their own nature, do have side effects. Currently, importing the CSS file into your project doesn't work in the production build -- since Webpack strips it out. 
The [Webpack docs](https://webpack.js.org/guides/tree-shaking/) state
> Note that any imported file is subject to tree shaking. This means if you use something like css-loader in your project and import a CSS file, it needs to be added to the side effect list so it will not be unintentionally dropped in production mode.
This PR simply adds the CSS files to the declaration so that. if imported, they make it to the final production bundle.
> chore(project): Add CSS files to sideEffects declaration

- lib/features/popup-menu/PopupMenu.js
- test/spec/features/popup-menu/PopupMenuSpec.js
Prevoiusly the popupMenu#create needed to be called when
context pad was opening. This is no longer needed. Now
only popupMenu#open needs to be called on context pad entry
click.
BREAKING CHANGES:
* popupMenu#create was removed
* popupMenu#open now expects element, id, position as params
* popupMenu#isEmpty now expects element, providerId as params
Fixes #253
> chore(popup-menu): allow multiple popupMenuProvider

- lib/features/popup-menu/PopupMenu.js
- test/spec/features/popup-menu/PopupMenuSpec.js
* A popup-menu entry can now accept multiple classes as `className` each of them delimited by a space, e. g. `className: 'class1 class2'`
> feat(popup-menu): support multiple classnames on popup-menu entries

- CHANGELOG.md
- lib/util/Text.js
- test/spec/features/popup-menu/PopupMenuSpec.js
- test/spec/util/TextSpec.js
This ensures we properly align text and support a numeric `lineHeight` property.
> feat(util/Text): make text-layouting lineHeight aware

- CHANGELOG.md
- lib/core/EventBus.js
- test/spec/core/EventBusSpec.js
The method `EventBus#on` allows us to register multiple event listeners at the same time:
```
eventBus.on([
'commandStack.changed',
'selection.changed'
], doStuff);
```
However, you're not able to un-register these events right now:
```
eventBus.off([
'commandStack.changed',
'selection.changed'
], doStuff);
// won't work :-(
```
This PR adresses this issue.
> feat(core/EventBus): allow #off to remove multiple event listeners

- lib/features/attach-support/AttachSupport.js
- lib/features/label-support/LabelSupport.js
- lib/features/modeling/cmd/helper/MoveClosure.js
- lib/features/modeling/cmd/helper/MoveHelper.js
- lib/util/Elements.js
- test/spec/features/attach-support/AttachSupportSpec.js
- test/spec/features/label-support/LabelSupportSpec.js
- test/spec/util/ElementsSpec.js
Prior to this change we adopted a complicated mechanism to move attachers and labels after the actual move closure.
This change simplifies the matter: We now add attachers and labels to the move closure and let our existing move mechanisms handle their movements, too.
As a result, users can rely on the fact that all elements moved once
* connection layouting is triggered
* the elements.move postExecute phase is triggered
:tada:
> refactor(modeling): move labels + attachers with closure

- lib/features/dragging/Dragging.js
- lib/features/replace/Replace.js
- test/spec/features/dragging/DraggingSpec.js
> 271 drag full pixel

- lib/features/context-pad/ContextPad.js
- test/spec/features/context-pad/ContextPadSpec.js
This PR adds default minimum and maximum scale of ContextPad and allows to set scaling for ContextPad in config.
Closes [#719](https://github.com/bpmn-io/bpmn-js/issues/719)
> 719 add minimum scale for context pad

- test/spec/features/context-pad/ContextPadSpec.js
The tests introduced in #282 didn't actually run. This PR fixes the problem. Also, bootstrapDiagram call was moved so that it's not repeated in the scaling tests any more.
> fix(context-pad): fix scaling tests

- lib/features/popup-menu/PopupMenu.js
- test/spec/features/popup-menu/PopupMenuSpec.js
Popup menu scaling is now globally configurable.
By default it does not scale below 1.0 and above 1.5.
Closes [#861](https://github.com/bpmn-io/bpmn-js/issues/861)
> feat(popup-menu): make scaling configurable with default min and max

- lib/features/context-pad/ContextPad.js
- lib/features/overlays/Overlays.js
- lib/features/popup-menu/PopupMenu.js
- package.json
- test/spec/features/context-pad/ContextPadSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
This PR:
* fixes an error if users omit _scale_ from the `popupMenu` and `contextPad` config
* reuses `isDefined` from `min-dash`
* bumps `min-dash` version, as the old version shipped with broken `{ isUndefined, isDefined }` helpers
> Reuse is defined

- lib/features/global-connect/GlobalConnect.js
- test/spec/features/global-connect/GlobalConnectSpec.js
- test/spec/features/global-connect/rules/GlobalConnectRules.js
- test/spec/features/global-connect/rules/index.js
This PR refactors GlobalConnect tool in order to make use of rules instead of hardcoded provider behaviour to determine whether the tool can be used with selected element.
* remove `GlobalConnect#registerProvider`
* use `connection.start` rule to determine whether
an element can start a connection
Closes [#565](https://github.com/bpmn-io/bpmn-js/issues/565)
BREAKING CHANGE:
* `GlobalConnect#registerProvider` got removed. Create
a rule for `connection.start` instead.
> feat(global-connect): use rules for canStartConnection

- lib/features/auto-resize/AutoResize.js
- lib/features/modeling/cmd/ReplaceShapeHandler.js
- test/spec/features/auto-resize/AutoResizeSpec.js
This PR fixes a problem which occurs when a collapsed element has children of bigger size than it is. Previously, the children would cover up the parent, making it unusable.
* AutoResize will now be activated whenever a collapsed element
is expanded unless the auto resizing is explicitly deactivated
* (ReplaceShape) Hints will be now passed to create a replacing shape to determine
if auto resizing should be fired.
* AutoResize will be fired when a child element is resized
unless hints disallow it.
Closes #287 
Closes [#786](https://github.com/bpmn-io/bpmn-js/issues/786)
> fix(auto-resize): resize collapsed element when it is expanded

- lib/.eslintrc
- package.json
This ensures we don't accidently require files in the lib directory
via the global `lib` import. That stuff works during tests but does
not work in the final bundle.
Considerations: This plugin adds some runtime overhead to our linting
process.
> chore(project): detect unresolved imports

- lib/features/editor-actions/EditorActions.js
- lib/features/editor-actions/index.js
- lib/features/keyboard-move-selection/KeyboardMoveSelection.js
- lib/features/keyboard/Keyboard.js
- lib/features/keyboard/KeyboardBindings.js
- lib/features/keyboard/index.js
- lib/navigation/keyboard-move/KeyboardMove.js
- lib/navigation/keyboard-move/index.js
- lib/navigation/movecanvas/MoveCanvas.js
- test/spec/features/editor-actions/EditorActionsSpec.js
- test/spec/features/keyboard-move-selection/KeyboardMoveSelectionSpec.js
- test/spec/features/keyboard/CopySpec.js
- test/spec/features/keyboard/KeyboardSpec.js
- test/spec/features/keyboard/PasteSpec.js
- test/spec/features/keyboard/ZoomSpec.js
- test/spec/navigation/keyboard-move/KeyboardMoveSpec.js
Refactors the editor actions to be independent from actual editor (or viewer) features, as discussed with @barmac.
Core features:
* only bind to actions in `EditorActions` which are implemented via features
* only register keyboard shortcuts for actions that are implemented via features
* rename `move-selection` to `keyboard-move-selection` for clarity
* adjust keyboard move selection config for clarity
* provide `EditorAction` Api for move selection feature
* expose key event via `keyEvent` property
Additional Benefit:
* EditorActions and Keyboard may now safely be used without pulling in the whole modeling code base.
> Editor action refactoring

- lib/features/keyboard/KeyboardBindings.js
- test/spec/features/keyboard/RemoveSelectionSpec.js
This PR adds [IE-specific](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values#Editing_keys) key value for `Delete` button.
Closes [#904](https://github.com/bpmn-io/bpmn-js/issues/904)
> fix(keyboard-bindings): add ie-specific key binding to remove selection

- test/spec/features/keyboard/KeyboardSpec.js
- test/util/KeyEvents.js
Drop target, as we cannot easily instantiate it.
Allow arbitrary attributes to initialize the event with.
> test(util/KeyEvents): simplify utility

- lib/features/grid-snapping/Grid.js
- lib/features/grid-snapping/GridSnapping.js
- lib/features/grid-snapping/index.js
- lib/features/resize/Resize.js
- lib/features/snapping/Snapping.js
- package-lock.json
- test/spec/features/grid-snapping/GridSnappingSpec.js
- test/spec/features/snapping/SnappingSpec.js
Snaps the following actions to a grid:
* creating/moving/resizing/connecting shapes
* moving bendpoints/connection segments
Furthermore, it:
* snaps with lower priority than snapping
* considers constraints when resizing shapes
Related to https://github.com/bpmn-io/bpmn-js/issues/973
> 1019 Add Basic Snap-to-Grid

- lib/features/grid-snapping/GridSnapping.js
- lib/features/grid-snapping/behavior/index.js
* grid snapping doesn't depend on its behavior module
* simplify implementation to be used by bpmn-io/bpmn-js#1003
Required by bpmn-io/bpmn-js#1003.
> Refactor Grid Snapping

- example/app/app.js
It seems that the example leads to confusion in some place since when moving one of the shapes (visually) connected by the example connection, the connection didn't get updated (cf. [forum thread](https://forum.bpmn.io/t/diagram-js-with-connectors/3360)):
This is _correct_ by design since the connection didn't get a `target` nor a `source` on creation. This pull request adds it to avoid confusion.
> fix(example): add source and target for example connection

- lib/features/auto-resize/AutoResize.js
- test/spec/features/auto-resize/AutoResizeSpec.js
As we've discussed using a generic hints object will allow us to pass more hints in the future.
> fix(auto-resize): allow passing hints

- lib/features/bendpoints/BendpointMove.js
- lib/features/bendpoints/BendpointMovePreview.js
- lib/features/bendpoints/BendpointSnapping.js
- lib/features/bendpoints/index.js
- lib/features/connect/ConnectPreview.js
- lib/features/connection-preview/ConnectionPreview.js
- lib/features/connection-preview/index.js
- lib/features/create/CreateConnectPreview.js
- test/spec/connection-preview/ConnectionPreviewSpec.js
- test/spec/features/bendpoints/BendpointsMoveSpec.js
- test/spec/features/connect/ConnectSpec.js
- test/spec/features/create/CreateSpec.js
This unifies connection preview features already implemented in several components (Bendpoints, Create, Connect/GlobalConnect) within ConnectionPreview. 
Related https://github.com/bpmn-io/bpmn-js/issues/744
> Consistently layout connections previews

- lib/features/bendpoints/BendpointUtil.js
- lib/features/bendpoints/ConnectionSegmentMove.js
- lib/layout/ManhattanLayout.js
- lib/util/Geometry.js
- test/spec/util/GeometrySpec.js
This was returning 'v' for horizontally-aligned lines and 'h' for vertically-aligned lines.
Added missing tests for `pointsAligned()`.
Also takes care of the width/height of the yellow parallel dragger SVG element and the direction of the dragger cursor when hovering over a line's parallel dragger area.
> fix(geometry): reverse truthy return values of `pointsAligned()`

- lib/features/create/Create.js
- test/spec/features/create/CreateSpec.js
This is useful for two cases:
1. Accessing and setting properties on the hints object in event handlers for create commands.
2. Sharing metadata between both event types.
> Allow setting and sharing of hints between create and commandStack.shape.create events

- lib/features/modeling/Modeling.js
- lib/features/modeling/cmd/ReconnectConnectionHandler.js
- lib/features/modeling/cmd/ReplaceShapeHandler.js
- test/spec/features/modeling/ReplaceShapeSpec.js
Simply pass hints with `layoutConnection=false` as the last param of `Modeling#replaceShape`.
> Allow to replace element without connection layout

- lib/features/bendpoints/BendpointMove.js
- lib/features/bendpoints/BendpointMovePreview.js
- lib/features/connection-preview/ConnectionPreview.js
- lib/layout/LayoutUtil.js
- test/spec/connection-preview/ConnectionPreviewSpec.js
- test/spec/features/bendpoints/BendpointsMoveSpec.js
- test/spec/features/bendpoints/rules/BendpointRules.js
- test/spec/layout/LayoutUtilSpec.js
This PR prevents such behavior:
> Remove redundant bendpoints from preview

- lib/features/bendpoints/BendpointMovePreview.js
- lib/features/connection-preview/ConnectionPreview.js
- lib/features/create/index.js
- test/spec/connection-preview/ConnectionPreviewSpec.js
- test/spec/features/bendpoints/BendpointsMoveSpec.js
- test/spec/features/connect/ConnectSpec.js
- test/spec/features/create/CreateSpec.js
This PR:
* removes dependency on css class in several tests
* recolors connection preview to black
* hides modified connection
* disables connection preview when dragging a new element
> Improve connection preview

- lib/features/create/Create.js
- lib/features/grid-snapping/GridSnapping.js
- lib/features/move/Move.js
- lib/features/resize/Resize.js
- lib/features/snapping/CreateMoveSnapping.js
- lib/features/snapping/ResizeSnapping.js
- lib/features/snapping/SnapContext.js
- lib/features/snapping/SnapUtil.js
- lib/features/snapping/Snapping.js
- lib/features/snapping/index.js
- test/spec/features/create/CreateSpec.js
- test/spec/features/grid-snapping/GridSnappingSpec.js
- test/spec/features/move/MoveSpec.js
- test/spec/features/resize/ResizeSpec.js
- test/spec/snapping/CreateMoveSnappingSpec.js
- test/spec/snapping/ResizeSnappingSpec.js
- test/spec/snapping/SnapUtilSpec.js
- test/spec/snapping/SnappingSpec.js
* allow constraining create (required by https://github.com/bpmn-io/bpmn-js/pull/1046/commits/5c83fbfa18b2a5b9d6a8bd24984c99a617f0b71e)
* prevent move/resize if unnecessary
* snap to borders on create/move
* add resize snapping
* separate create/move snapping integration from core snapping
Required by https://github.com/bpmn-io/bpmn-js/pull/1046.
Related to https://github.com/camunda/camunda-modeler/issues/1290.
> Snap During Resize

- lib/features/create/Create.js
- lib/features/move/Move.js
- test/spec/features/create/CreateSpec.js
- test/spec/features/create/rules/CreateRules.js
- test/spec/features/move/MovePreviewSpec.js
- test/spec/features/move/rules/MoveRules.js
Allow ignoring `.new-parent` overlay visually by setting `canExecute` to `null` 
Related to bpmn-io/bpmn-js#1065
> Ensure visually ignored / always on top movement is possible

- lib/i18n/translate/translate.js
- lib/util/EscapeUtil.js
- test/spec/i18n/translate/translateSpec.js
- test/spec/util/EscapeUtilSpec.js
This makes sure that we escape translations per default to avoid XSS issues with i18n. Pass `safe=true` if the input is already safe.
> feat(i18n): escape translations per default

- lib/i18n/translate/translate.js
- lib/util/EscapeUtil.js
- test/spec/i18n/translate/translateSpec.js
- test/spec/util/EscapeUtilSpec.js
This mixes the two concerns escaping + translating and causes issues in places where escaping is not desired.
Needs to be re-assessed. 
Reverts bpmn-io/diagram-js#363
> Revert "feat(i18n): escape translations per default"

- lib/util/EscapeUtil.js
- test/spec/util/EscapeUtilSpec.js
This PR introduces `EscapeUtil` improvement which is part of https://github.com/bpmn-io/diagram-js/pull/366 but without the i18n changes.
> feat(util): properly escape html entities

- lib/features/bendpoints/BendpointUtil.js
- lib/features/bendpoints/Bendpoints.js
- lib/features/bendpoints/ConnectionSegmentMove.js
- lib/features/interaction-events/InteractionEvents.js
- test/spec/features/bendpoints/BendpointsSpec.js
- test/spec/features/bendpoints/ConnectionSegmentMoveSpec.js
Parallel movement was previously possible only when hovering and clicking on the connection's center, within a hard-coded threshold of 10px.
The move region is two-thirds of a connection segment's length measured from the center of that segment.
The move activation threshold is now half of that region.
__Which issue does this PR address?_
Related to camunda/camunda-modeler#1197
> Improve parallel segment moving

- assets/diagram-js.css
- lib/features/attach-support/AttachSupport.js
- test/spec/features/attach-support/AttachSupportSpec.js
The (potential) host's hit shape will now grow so that it gives a _stickiness_ effect. When merged, this will fix https://github.com/bpmn-io/bpmn-js/issues/1078.
> Make hosts sticky for valid attachments

- lib/features/bendpoints/Bendpoints.js
- test/spec/features/bendpoints/BendpointsSpec.js
This prevents updating the segment dragger and starting segment move on bendpoint intersections (cf. `intersection.bendpoint === true`). 
Closes bpmn-io/bpmn-js#1096
Closes #369
> Segment Dragger fixes

- assets/diagram-js.css
This improves our drag preview styles for text.
Until now, text is rendered clumsy: 
With this change, text is rendered crisp when dragging:
> feat(styles): improve dragger text styles

- CHANGELOG.md
We missed the reason why it's going to be a major version. This PR adds the breaking change to the changelog.
> chore(CHANGELOG): update with breaking change

- lib/features/snapping/CreateMoveSnapping.js
- test/spec/snapping/CreateMoveSnappingSpec.js
Removing the default TRBL snapping in favor of fine-grained
control in using applications.
Related to https://github.com/bpmn-io/bpmn-js/issues/1104
> chore(snapping): remove default top-left / bottom-right snaps

- lib/core/GraphicsFactory.js
- test/spec/core/GraphicsFactorySpec.js
Prepending a node to itself blows up in Internet Exploder. 💥 
Related to bpmn-io/bpmn-js#746
> fix(graphics-factory): don't update containments if less than 2 children

- lib/core/GraphicsFactory.js
- test/spec/core/GraphicsFactorySpec.js
* always update
* do not prepend to self
Closes bpmn-io/bpmn-js#1129
Related to https://github.com/bpmn-io/bpmn-js/issues/746
> fix(graphics-factory): do not prepend to self

- lib/features/dragging/HoverFix.js
- test/spec/features/dragging/HoverFixSpec.js
This ensures we definitely fire an `element.out` event between two `hover` for different elements. This way we make sure cursor and marker cleanup really got to run, despite the fact [some browsers swallow certain `mouseout` events](http://stackoverflow.com/questions/7448468/why-cant-i-reliably-capture-a-mouseout-event).
Related to camunda/camunda-modeler#1383
> Ensure firing out event

- lib/features/selection/SelectionBehavior.js
- test/spec/features/selection/SelectionSpec.js
Adds `autoSelect` hint for specifying elements that should be selected after create. Setting `autoSelect` to `false` will not select any elements.
Related to bpmn-io/bpmn-js#1152
> Select All Elements after Creating Elements

- lib/features/modeling/cmd/CreateElementsHandler.js
- test/spec/features/modeling/CreateElementsSpec.js
This ensures created elements will not have fractional coordinates after creating.
Closes bpmn-io/bpmn-js#1167
> fix(modeling): prevent fractional coordinates after create

- lib/features/snapping/CreateMoveSnapping.js
- test/spec/snapping/CreateMoveSnappingSpec.js
Related to https://github.com/bpmn-io/bpmn-js/issues/1165
> Disable snapping to diagram origin on create

- lib/features/palette/Palette.js
The current palette implementation is flawed in a way that the parent
it mounts to cannot easily be overridden.
There exists the method Palette#_getParentContainer that serves the
purpose, however it is not being used in the palettes initialization
function.
This PR fixes this behavior.
> chore(palette): use existing parent getter when initializing

- lib/features/create/Create.js
- lib/features/dragging/HoverFix.js
- test/spec/features/create/CreateSpec.js
- test/spec/features/dragging/HoverFixSpec.js
This sets the create target on every hover. We ensure via `HoverFix` that we always have a target to create on.
It also cleans up the existing `HoverFix` to ensure it
* executes after one  `drag.move` (as it worked before with the current use of the `eventBus`)
* offers a better test case to actually test the hovering, cf. [Hour Of Code](https://github.com/bpmn-io/hour-of-code/commit/cacaf6808213da7286db3e8322eb8f4a31f7e2c4)
Related to camunda/camunda-modeler#1467
> Set target on create.hover

- lib/features/create/Create.js
- lib/features/dragging/HoverFix.js
- test/spec/features/dragging/HoverFixSpec.js
After merging the fixes from https://github.com/bpmn-io/diagram-js/pull/400 and https://github.com/bpmn-io/diagram-js/pull/399 pasting-without-moving was not possible inside the `rootElement` since the `target` got removed [via the next `create.move`](https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/create/Create.js#L144). This got fired [without the updated dragContext](https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/dragging/Dragging.js#L171) (it is using the old event context without the updated hover, therefore hover is still undefined in this case).
It is working fine inside container elements since the browser fires an additional `hover` event due to the `pointer-event` changes by setting and unsetting the `.djs-drag-active` class.
This pull request …
> Fixup create

- lib/features/dragging/HoverFix.js
- test/spec/features/dragging/HoverFixSpec.js
* do not declare variables inside scope (not supported in ES5)
* verity correct hover element is set by HoverFix
> chore(dragging): style fixes + more robust test

- lib/features/copy-paste/CopyPaste.js
- test/spec/features/copy-paste/CopyPasteSpec.js
- test/spec/features/copy-paste/rules/CopyPasteRules.js
Linked to: https://github.com/bpmn-io/bpmn-js/pull/1192
This PR helps creating host attachments using copyPaste module, especially useful for tests.
A **hints** object can be provided to context parameter:
The same feature exists already for modeling.createShape API.
> feat(copy-paste): allow host attachment using copyPaste.paste API

- lib/command/CommandStack.js
- test/spec/command/CommandStackSpec.js
1. Command handler A returns dirty shape A with ID `foo`
2. Command handler B returns dirty shape B with ID `foo`
3. `elements.changed` will be fired with shape A even though the latest changed element with ID `foo` was shape B
Replacement (while keeping the ID) is one of the cases where this becomes a problem.
Related to bpmn-io/bpmn-js#1207.
> fix(command): return latest changed elements

- lib/features/create/Create.js
- test/spec/features/create/CreateSpec.js
* cancel create on `elements.changed`
Related to camunda/camunda-modeler#1466
> fix(create): cancel create on <elements.changed>

- lib/features/create/Create.js
- lib/features/dragging/Dragging.js
- test/spec/features/dragging/DraggingSpec.js
This PR filters out the non-existing elements when restoring selection on dragging cancelation.
Related to https://github.com/bpmn-io/bpmn-js/issues/1225
> Restore selection correctly

- karma.conf.js
Source maps are really helpful when debugging and don't significantly change the bundle time.
> chore(project): use source maps in tests

- lib/features/popup-menu/PopupMenu.js
- test/spec/features/popup-menu/PopupMenuSpec.js
This fixes a wrong listener being unsubscribed from events. Not sure though, if we should actually listen for context pad events in that place.
> Correctly unsubscribe auto-close handler

- lib/core/EventBus.js
- lib/features/context-pad/ContextPad.js
- lib/features/palette/Palette.js
- lib/features/popup-menu/PopupMenu.js
- test/spec/core/EventBusSpec.js
- test/spec/features/context-pad/ContextPadSpec.js
- test/spec/features/palette/PaletteSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
Closes #428
Note: This breaks multiple test cases in `bpmn-js`, but all of the failures base on checking the internals. I'll prepare a fix for that.
> Improve entries apis: Context Pad, Palette, Popup Menu

- lib/features/attach-support/AttachSupport.js
- lib/features/bendpoints/BendpointMove.js
- lib/features/bendpoints/BendpointMovePreview.js
- lib/features/bendpoints/BendpointSnapping.js
- lib/features/connect/Connect.js
- lib/features/connect/ConnectPreview.js
- lib/features/connection-preview/ConnectionPreview.js
- lib/features/modeling/Modeling.js
- lib/features/modeling/cmd/ReconnectConnectionHandler.js
- lib/features/modeling/cmd/ReplaceShapeHandler.js
- test/spec/features/attach-support/AttachSupportSpec.js
- test/spec/features/attach-support/rules/AttachRules.js
- test/spec/features/bendpoints/BendpointsMoveSpec.js
- test/spec/features/bendpoints/rules/BendpointRules.js
- test/spec/features/connect/ConnectSpec.js
- test/spec/features/connect/rules/ConnectRules.js
- test/spec/features/global-connect/GlobalConnectSpec.js
- test/spec/features/modeling/ReconnectConnectionSpec.js
Closes https://github.com/bpmn-io/diagram-js/issues/386
> Connect Reverse

- package-lock.json
- package.json
This updates the [path-intersection](https://github.com/bpmn-io/path-intersection) library we use for clipping to the latest version (v2.0.1). Features: 
* smaller bundle size
* numerous intersection detection improvements
---
Using the `MoveStressSpec` in bpmn-js I was able to verify that the new version of path-intersection leads to a significant reduction in _intersection cannot be found errors_: 
```
#2404 rate=0.389351081530782, no-intersections=936
#2413 rate=0.009117281392457521, no-intersections=22
```
---
Here is a screenshot of the impossible: Newer version, even smaller bundle sizes!
> chore(project): update to path-intersection@2

- lib/features/modeling/cmd/ReplaceShapeHandler.js
- lib/features/replace/Replace.js
- test/spec/features/replace/ReplaceSpec.js
* re-compute correct incoming and outgoing anchors when replacing a
shape with different bounds
* make it possible for Replace to take bounds
Related to https://github.com/bpmn-io/bpmn-js/issues/1265
> feat(replace): update incoming and outgoing anchors

- lib/features/copy-paste/CopyPaste.js
- test/spec/features/copy-paste/CopyPasteSpec.js
__Addresses https://github.com/bpmn-io/bpmn-js/issues/1270__
Hidden and collapsed elements are now pasted correctly, however, three problems remain.
1. The preview is not generated correctly. 
2. Labels are pasted incorrectly and are not visible. However, this bug appears to happen because the parent reference is not set correctly, similar to https://github.com/bpmn-io/bpmn-js/issues/945. Because the label becomes the child of the root element, it is never unhidden, when its actual  collapsed parent is expanded. This issue also happens by just collapsing, moving and uncollapsing a subprocess, unrelated to copy-pasting. 
3. After paste the sequence flow is selectable, however, once the root element has been selected, it is no longer selectable and correctly inside the actual parent shape. …
> fix(copy-paste) Copy hidden and collapsed properties when copy-pasting.

- lib/features/auto-place/AutoPlace.js
- lib/features/auto-place/AutoPlaceSelectionBehavior.js
- lib/features/auto-place/AutoPlaceUtil.js
- lib/features/auto-place/index.js
- lib/features/create/Create.js
- lib/features/modeling/Modeling.js
- lib/features/modeling/cmd/AppendShapeHandler.js
- test/spec/features/auto-place/AutoPlaceSpec.js
- test/spec/features/create/CreateSpec.js
- test/spec/features/create/rules/CreateRules.js
- test/spec/features/modeling/AppendShapeSpec.js
* allow connecting from new shape to source on append
* add auto-place feature
Required by https://github.com/bpmn-io/bpmn-js/pull/1284
Required by https://github.com/bpmn-io/dmn-js/pull/481
> Add Auto-Place Feature

- lib/features/space-tool/SpaceTool.js
- test/spec/features/space-tool/SpaceToolSpec.js
Related to camunda/camunda-modeler#1703
Required by https://github.com/bpmn-io/bpmn-js/pull/1291
> chore(space-tool): provide context when getting minimum dimensions

- karma.conf.js
Custom Chrome launcher on Linux is not needed anymore (as of 2020).
> test(project): remove legacy CI hack

- lib/features/auto-place/AutoPlaceUtil.js
- lib/features/bendpoints/BendpointMove.js
- lib/features/bendpoints/BendpointMovePreview.js
- lib/features/connect/ConnectPreview.js
- lib/features/modeling/cmd/ReconnectConnectionHandler.js
- test/spec/features/auto-place/AutoPlaceSpec.js
- test/spec/features/bendpoints/BendpointsMoveSpec.js
- test/spec/features/modeling/ReconnectConnectionSpec.js
BREAKING CHANGES
* rename `deconflictPosition` to `getFreePosition` and change API
* change `getConnectedDIstance` API
Required by https://github.com/bpmn-io/dmn-js/pull/492
> Enable Top-Down Modeling

- lib/features/auto-place/AutoPlaceUtil.js
- test/spec/features/auto-place/AutoPlaceSpec.js
Closes #458 
Required by https://github.com/bpmn-io/bpmn-js/pull/1284
> fix(auto-place): fix east and west in #getConnectedDistance

- lib/features/keyboard/KeyboardBindings.js
- lib/features/keyboard/KeyboardUtil.js
- test/spec/features/keyboard/CopySpec.js
- test/spec/features/keyboard/PasteSpec.js
- test/spec/features/keyboard/RedoSpec.js
- test/spec/features/keyboard/UndoSpec.js
Using `keyCode` as a fallback ensures that the keyboard bindings work on keyboards other than QWERTY. I've successfully tested it using a Russian keyboard layout.
Closes https://github.com/bpmn-io/diagram-js/pull/456
> feat(keyboard): use keyCode as fallback

- test/spec/features/rules/priority-rules/PriorityRules.js
Related to https://go-review.googlesource.com/c/go/+/236857/
> There's been plenty of discussion on the usage of these terms in tech.
> I'm not trying to have yet another debate. It's clear that there are
> people who are hurt by them and who are made to feel unwelcome by their
> use due not to technical reasons but to their historical and social
> context. That's simply enough reason to replace them.
> 
> Anyway, allowlist and blocklist are more self-explanatory than whitelist
> and blacklist, so this change has negative cost.
> 
> Didn't change vendored, bundled, and minified files. Nearly all changes
> are tests or comments, with a couple renames in cmd/link and cmd/oldlink
> which are extremely safe. This should be fine to land during the freeze
> without even asking for an exception. …
> Replace whitelist/blacklist with allowlist/blocklist

- lib/features/touch/TouchInteractionEvents.js
Fixes touch bugs that occur frequently in Sentry (https://sentry.io/organizations/camunda-modeling/issues/1640119817/?project=5218065&query=is%3Aunresolved&statsPeriod=24h)
For the solution, see: https://stackoverflow.com/questions/26027362/how-to-stoppropagation-w-hammer-js-2-0
I tested this with my iPhone and can confirm it works. One can also test this with XCode iPhone simulator & remote debugging via Safari on MacOS devices.
> Correctly handle stopPropagation for iphone and ipad devices

- lib/features/keyboard/KeyboardBindings.js
- test/spec/features/keyboard/ZoomSpec.js
This is required for the feature to work on international
keyboard layout.
Related to https://github.com/bpmn-io/bpmn-js/issues/1362
__Acceptance Criteria__
> fix(keyboard): bind zoom in to `=` key

- lib/util/Text.js
- test/spec/util/TextSpec.js
This adds handling for discretionary hyphens / soft breaks in our renderer.
If a discretionary hyphen is rendered as a break point it becomes a `-`.
Related to https://github.com/bpmn-io/bpmn-js/issues/1383
---
> feat(util/Text): support soft breaks

- lib/features/bendpoints/BendpointMovePreview.js
- test/spec/features/bendpoints/BendpointsMoveSpec.js
This reverts https://github.com/bpmn-io/diagram-js/commit/66b77964ba692dc7da5454d7855a9043de88f89b. The fix looked simple enough but actually introduced some [unwanted side-effects](https://travis-ci.com/github/bpmn-io/bpmn-js/builds/208964265).
Specifically we do rely on `connectionPreview` to attach `getConnection` to the bendpoint move context in our tests, both in diagram-js as well as bpmn-js. 
While this is shaky in the first place (relying on an internal just like that) I'd rather revert the fix now and investigate an appropriate solution in an orderly manner.
I'll investigate if I can find a more appropriate solution.
> Revert bendpoint preview quick fix

- lib/features/global-connect/GlobalConnect.js
- lib/features/global-connect/index.js
- lib/features/hand-tool/HandTool.js
- lib/features/hand-tool/index.js
- lib/features/lasso-tool/LassoTool.js
- lib/features/lasso-tool/index.js
- lib/features/space-tool/SpaceTool.js
- lib/features/space-tool/index.js
- lib/features/tool-manager/ToolManager.js
- test/spec/features/global-connect/GlobalConnectSpec.js
- test/spec/features/hand-tool/HandToolSpec.js
- test/spec/features/lasso-tool/LassoToolSpec.js
- test/spec/features/space-tool/SpaceToolSpec.js
A long standing UX issue in our toolkit is the fact that tool activation (hand tool, lasso tool, space tool, global connect tool) via keyboard shortcuts is wonky. Due to the fact that a mouse event is missing during keyboard activation actual visual feedback is only displayed after the first mouse move interaction.
A couple of related bugs have been filed in the past regarding this: https://github.com/bpmn-io/diagram-js/issues/136, https://github.com/bpmn-io/bpmn-js/issues/584, https://github.com/camunda/camunda-modeler/issues/664, https://github.com/camunda/camunda-modeler/issues/1229.
Since the rework of copy and paste (and the introduction of two-step copy and paste) we have the means to fix this issue: Automatically activate the tools using the last mouse position recorded by our …
> Activate tools immediately using last good known mouse event

- lib/features/bendpoints/Bendpoints.js
- lib/features/hand-tool/HandTool.js
- lib/features/interaction-events/InteractionEvents.js
- lib/features/lasso-tool/LassoTool.js
- lib/features/move/Move.js
- lib/features/selection/SelectionBehavior.js
- lib/navigation/movecanvas/MoveCanvas.js
- lib/util/Mouse.js
- test/spec/features/bendpoints/BendpointsSpec.js
- test/spec/features/hand-tool/HandToolSpec.js
- test/spec/features/interaction-events/InteractionEventsSpec.js
- test/spec/features/lasso-tool/LassoToolSpec.js
- test/spec/features/move/MoveSpec.js
- test/spec/features/selection/SelectionBehaviorSpec.js
- test/spec/navigation/movecanvas/MoveCanvasSpec.js
- test/util/MockEvents.js
Support middle mouse button canvas move like other state of the art drawing tools support it.
* Introduces ability for interaction events to forward middle mouse button mouse events
* updates behaviors to handle that case accordingly
* increases test coverage around mouse activation in the tools that use `element.*` events
* make `MoveCanvas` react to middle mouse button
Interestingly our existing behavior to "prevent clicks" is not needed when dragging and dropping using the middle mouse button (tested in Firefox and Chromium). I had to make the existing fix somewhat more specific to only catch left mouse button interactions (https://github.com/bpmn-io/diagram-js/commit/0d1c964eebd4c8ffdc090ce3d472605b35396a43).
This introduces a _breaking change_: Previously we'd only pipe left mouse …
> Middle mouse button canvas move

- .travis.yml
- karma.conf.js
- test/spec/features/global-connect/GlobalConnectSpec.js
- test/spec/features/hand-tool/HandToolSpec.js
- test/spec/features/lasso-tool/LassoToolSpec.js
- test/spec/features/space-tool/SpaceToolSpec.js
Run against both, ChromeHeadless and PhantomJS in CI to have each one covered.
> chore: make ChromeHeadless our default test browser

- test/spec/features/palette/PaletteSpec.js
Adds test cases for the tool highlighting on the palette. Skips the tests for phantom-js.
Rationale (cf. https://github.com/bpmn-io/diagram-js/pull/515#issue-550333421)
> * min-dash#forEach will handle HTMLCollection as objects
> * in phantom-js, it also iterates over the length property of the children collection
> --> crashes on the next line when trying to access HTML attributes from a non-DOM element
> test(palette): add test cases for tool highlighting

- test/TestHelper.js
- test/helper/index.js
- test/spec/core/CanvasSpec.js
- test/spec/features/bendpoints/BendpointsSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
This improves the test container markup we generate (and expose) via our helpers https://github.com/bpmn-io/diagram-js/commit/36983303bb6ea10fd76f4a5e4d05c37be35090cf.
Also, https://github.com/bpmn-io/diagram-js/commit/9b3d28166f0f6ba7be9a10a2fd6ea3c6e7558de3 our tests run stable against all target browsers currently tested headless.
> test: do not double add test-container class

- .github/workflows/CI.yml
- .npmignore
- .travis.yml
- README.md
Run test suite against all browsers on GitHub actions.
Rename ci -> CI to match upper case build action naming conventions.
Remove Travis CI :skull:
> chore: fully migrate to GitHub actions

- assets/diagram-js.css
__Which issue does this PR address?__
We accidentally placed the stroke color in the wrong place while we updated the color palette (cf. https://github.com/bpmn-io/diagram-js/issues/476, [these lines of code](https://github.com/bpmn-io/diagram-js/commit/c206608bcef920e0770393fb3b3641fe52322072#diff-682322eea3bdf2a0256e2e37fb5a12ac5c9744f340488edcb053b4dbe8f57137R149-R155)).
**Before**
**After**
Related to https://github.com/bpmn-io/bpmn-js/issues/1380
__Acceptance Criteria__
> Correct stroke colors

- lib/command/CommandStack.js
- test/spec/command/CommandStackSpec.js
This allows consumers to understand the root cause of a command execution, may it be `execute`, `undo`, `redo` or `clear`.
> Add trigger to commandStack.changed event

- assets/diagram-js.css
A fill opacity is already applied for any solid element.
Adding additional opacity on drop allowed (or disallowed) causes quite some visual noise.
---
Try it out via 
```
npx @bpmn-io/sr bpmn-io/bpmn-js -l bpmn-io/diagram-js#solid-bg-colors
```
> fix: use solid background colors for drop indicators

- CHANGELOG.md
- lib/features/align-elements/AlignElements.js
- test/spec/features/align-elements/AlignElementsSpec.js
This ensures we do not put an action onto the command stack if we do not do anything: Less than two elements cannot be aligned.
> Align min two

- lib/core/Canvas.js
- lib/features/auto-place/AutoPlace.js
- lib/features/search-pad/SearchPad.js
- test/spec/core/CanvasSpec.js
- test/spec/features/auto-place/AutoPlaceSpec.js
- test/spec/features/search-pad/SearchPadSpec.js
* adjust AutoPlace to scroll to new element
* adjust SearchPad to use centralized function
related to https://github.com/camunda/camunda-modeler/issues/1249
replaces https://github.com/bpmn-io/bpmn-js/pull/1437
> feat(canvas): add #scrollToElement function

- lib/features/connect/ConnectPreview.js
- test/spec/features/connect/ConnectSpec.js
Fixes preview when connecting the start event with a message flow. Example of broken behavior:
fixed:
related to https://github.com/bpmn-io/bpmn-js/issues/1431
> fix(preview): fix preview for reversed flows

- .npmignore
- package.json
This introduces `package.json#files` field as a replacement to `.npmignore`.
Benefits:
* you don't need to update any files when you add random files to repo
* you don't need to exclude coverage
* you don't need to exclude CI configuration
How to test this:
```sh
git checkout develop
npm pack --dry-run 2> before
git checkout use-package-json-files
npm pack --dry-run 2> after
diff -y before after | less
```
> Use package json files

- README.md
I implemented an object diagram viewer and editor based on diagram-js.
I would like it to be included in the external examples.
> Added new external example object diagram modeler to the README.

- lib/core/Canvas.js
- test/spec/core/CanvasSpec.js
**What is the problem?**
- on `diagram.clear` the planes are not cleared
- Therefore, re-import of the same diagram is not possible if it tries to create the same plane again (related to [BPMNImporter PR](https://github.com/bpmn-io/bpmn-js/blob/fe1005bea417c3fb4a9ea235cffc995ffa7fdc90/lib/import/BpmnImporter.js#L115-L120))
- Root elements are set to `null` on existing diagrams, but not populated with an implicit root by default (related to https://github.com/bpmn-io/dmn-js-properties-panel/issues/23)
**Fix**
on `diagram.clear`:
- Remove all planes 
- Reset active Plane
> fix(canvas): remove all planes on `diagram.clear`

- assets/diagram-js.css
This ensures the `.djs-search-input` always uses the full width of the border box.
_before_
_after_
> style: adjust search input

- lib/core/Canvas.js
- test/spec/core/CanvasSpec.js
This reverts commit 058731b3ae12f9ae278a6d906b62b8bedd44270f and uses a positive index to place resize layers infront of rendered content
**Why we need to revert:**
- This commit broke the [integration tests](https://github.com/bpmn-io/bpmn-js-integration/actions/runs/1425366500) because we did not consider to set the plane index when only accessing layers (not planes)
- It broke the API that [negative indexes are rendered below](https://github.com/bpmn-io/diagram-js/blob/9b77f3a250b88d712e1056e8a0d738f57143228b/test/spec/core/CanvasSpec.js#L2029) and [positive indexes are rendered above](https://github.com/bpmn-io/diagram-js/blob/9b77f3a250b88d712e1056e8a0d738f57143228b/test/spec/core/CanvasSpec.js#L2043) the base layer
Instead of lowering the index of planes, we should use the existing …
> fix(core): ensure base layer has index 0

- assets/diagram-js.css
Closes #581
This replaces the existing color scheme with the new, reduced one [of the Camunda Modeler](https://github.com/camunda/camunda-modeler/issues/2459#issuecomment-951977843).
To try it out
```sh
npx @bpmn-io/sr bpmn-io/bpmn-js#develop -l bpmn-io/diagram-js#581-reduced-color-scheme
```
-----
Note: I had to add one color for the opacity blue (bendpoints, resize markers, search result overlay ...).
```css
--color-blue-205-100-45-opacity-30: hsla(205, 100%, 45%, 30%);
```
> style: update color scheme

- lib/features/palette/Palette.js
- test/spec/features/palette/PaletteSpec.js
closes #591
- we still keep the classes on `.djs-palette` to not break existing css adjustments
- also expose `djs-palette-available` to differentiate no palette and closed palette
> feat(palette): expose pallete state to djs-container

- lib/features/palette/Palette.js
- test/spec/features/palette/PaletteSpec.js
Let us rename `available` to `shown`. It better matches the fact that the palette is on the Canvas (and must be reacted to). 
Let us also patch release this before things get widely adopted :+1:
> chore(palette): rename available -> shown

- lib/core/Canvas.js
- test/spec/core/CanvasSpec.js
Allows the use of planes in the viewer without including `diagram-js.css`
> fix(canvas): ensure planes work without diagram-js.css

- lib/core/Canvas.js
- lib/core/ElementRegistry.js
- test/spec/core/CanvasSpec.js
- test/spec/core/ElementRegistrySpec.js
This enables us to remove planes, e.g. when they are renamed.
This is used in https://github.com/bpmn-io/bpmn-js/pull/1538. Example use case here:
https://github.com/bpmn-io/bpmn-js/blob/0370ae612341d2c20227bb6b20bfd9fb6f2669c9/lib/features/modeling/behavior/SubProcessPlaneBehavior.js#L155-L173
> feat(canvas): allow removing planes

- lib/core/Canvas.js
- lib/features/overlays/Overlays.js
- lib/features/planes/PlanesBehavior.js
- lib/features/planes/index.js
- lib/features/root-elements/RootElementsBehavior.js
- lib/features/root-elements/index.js
- lib/features/selection/Selection.js
- test/spec/command/CommandStackSpec.js
- test/spec/core/CanvasSpec.js
- test/spec/features/interaction-events/InteractionEventsSpec.js
- test/spec/features/overlays/OverlaysSpec.js
- test/spec/features/palette/PaletteSpec.js
- test/spec/features/planes/PlanesBehaviorSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
- test/spec/features/root-elements/RootElementsBehaviorSpec.js
- test/spec/features/selection/SelectionSpec.js
- test/spec/features/tooltips/TooltipsSpec.js
This adds the capability to add multiple root elements to the Canvas. 
As a side-effect, it drops our leaky plane abstraction from the public 
API.
The following `Canvas` APIs make the magic happen:
* `Canvas#addRootElement` - add a root element without showing it
* `Canvas#removeRootElement` - remove a root element
* `Canvas#setRootElement` - set to a specific root element; for 
backwards compatibility the add-during-set semantic is kept
* `Canvas#getRootElements` - returns a list of root elements that can 
be switched to
Under the hood we continue to rely on root element specific layers.
However, we clean these layers up once the root element is removed.
---
* All plane related APIs got removed, use the newly introduced
`(add|set)RootElement` APIs to accomplish the same thing.
* …
> feat: make truely multi-root aware

- lib/features/overlays/Overlays.js
- test/spec/features/overlays/OverlaysIntegrationSpec.js
When a shape is moved to another root element, the overlay should move with it. This PR ensures that we don't use outdated rootElement info when calculating visibility
> fix(overlays): add multi-root modeling behavior

- lib/features/touch/TouchInteractionEvents.js
fixes upstream bpmn-io/bpmn-js#618
* testing infrastructure is not set up here. Hence I am skipping the
testing bit due to time contraints (we do not reduce quality). 
* For sure we need to set up proper testing infrastrcture, when reworking the
entire touch module.
* manual integration test done with bpmn-js direct editing module and
ipad safari
> fix(touchInteractionEvents): fire dblClick with button=1

- assets/diagram-js.css
related to https://github.com/bpmn-io/bpmn-js/issues/1564
This is caused by referencing a non-existing color variable. I used `color-blue-205-100-45-opacity-30` instead of adding a new one as the existing one is very close to the requested one
> fix(snapping): use existing color variable

- lib/features/overlays/Overlays.js
- test/spec/features/overlays/OverlaysSpec.js
Overlay update fails when `show` is used, because the viewbox is missing here: https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/overlays/Overlays.js#L489-L492
I adjusted existing tests to fail in this scenario instead of creating new ones.
closes #614
> fix(overlays): ensure overlays update on root change

- lib/core/Canvas.js
- test/spec/core/CanvasSpec.js
This PR fixes the following scenario:
1. In bpmn-js, we import all diagrams without setting an active root element
2. Once all imports are done, we set the root element (either a process or subprocess)
3. If an extensions reacts to `shape.add` during import and uses `canvas.getRootElement()`, an implicit root is created
Therefore, we do not want to create implicit roots when root elements are already present but not active.
We still ensure that we support simple use-cases, where no explicit root element is needed.
> fix(canvas): `getRootElement` returns null during import

- lib/features/keyboard/Keyboard.js
Webpack polyfills `array.includes`, so our phantomJS tests are green even when they should not be.
https://github.com/bpmn-io/diagram-js/blob/develop/package-lock.json#L3385
> fix(keyboard): don't use ES6 code

- lib/core/Canvas.js
- test/spec/core/CanvasSpec.js
For performance reasons, we only want to have layers of visible object present in the DOM tree. For the reasoning behind it, please see the comment in the platform repo: https://github.com/camunda/camunda-modeler/issues/2803#issuecomment-1059163820
You can now:
- Hide layers (internal implementation: remove them from the DOM tree)
- Show layers (internal implementation: add them to the DOM tree again)
By default, every layer is visible. We explicitly have to hide them, e.g. when adding an inactive `rootElement`
> feat(canvas): add API to hide/show layers

- assets/diagram-js.css
The current context pad styles are prone to break in environments where line-height is != 1.
I.e. reproducible on `demo.bpmn.io` if `body { line-height: 10; }` is added as a CSS directive.
This PR fixes the behavior; it also ensures that mixed images + icon fonts (appropriately sized) are aligned:
_Chrome_
_Firefox_
> fix(context-pad): robust position in line-height != 1 scenarios

- CHANGELOG.md
- assets/diagram-js.css
Backports https://github.com/bpmn-io/diagram-js/pull/630 to `7.x`.
> fix(context-pad): robust position in line-height != 1 scenarios #630

- assets/diagram-js.css
- test/spec/features/palette/PaletteSpec.js
_This corrects the spacing of the palette separator:_
---
_Here is an example with a complex palette (mix of icon font (`:before`) + image entries:_
> fix(palette): correct separator spacing

- lib/core/Canvas.js
- lib/features/overlays/Overlays.js
- lib/features/popup-menu/PopupMenu.js
- lib/features/search-pad/SearchPad.js
- lib/features/tooltips/Tooltips.js
- lib/util/Text.js
- package-lock.json
- package.json
- test/spec/features/overlays/OverlaysSpec.js
- test/spec/features/tooltips/TooltipsSpec.js
This PR removes all inline styles and replaces them with direct assignment to Comply with CSP style-src.
Related to https://github.com/bpmn-io/bpmn-js/issues/1625
> fix: comply with style-src CSP

- CHANGELOG.md
- assets/diagram-js.css
- lib/features/interaction-events/InteractionEvents.js
- lib/features/move/Move.js
- test/spec/features/move/MoveSpec.js
Use `no-move` type of hit box to disable element movement via hit box.
Related to https://github.com/camunda/camunda-modeler/issues/2859
Test with:
`npx @bpmn-io/sr bpmn-io/bpmn-js#improve-selection-of-a-pool -l bpmn-io/diagram-js#improve-selection-of-a-pool`
> Add hit box to disable move interaction

- assets/diagram-js.css
- lib/features/context-pad/ContextPad.js
- lib/features/overlays/Overlays.js
- lib/features/selection/SelectionVisuals.js
- lib/util/Elements.js
- test/spec/features/context-pad/ContextPadProvider.js
- test/spec/features/context-pad/ContextPadSpec.js
- test/spec/features/selection/SelectionVisualsSpec.js
- test/util/MockEvents.js
Adds the ability to create a context pad around more than one element:
---
Capture of the thing in action for "delete" example (with reaction to undo/redo): 
https://user-images.githubusercontent.com/25825387/169019635-83b14574-1a2f-4eaa-b603-645ee357fb50.mov
Delete can be tested by using https://github.com/bpmn-io/bpmn-js/pull/1525 and linking this instance of diagram-js
Closes https://github.com/bpmn-io/diagram-js/issues/278
> Add ability to provide context pads for multiple elements

- lib/features/connect/Connect.js
- lib/features/resize/ResizeHandles.js
- lib/features/selection/SelectionBehavior.js
- test/spec/features/connect/ConnectSpec.js
- test/spec/features/resize/ResizeSpec.js
- test/spec/features/selection/SelectionBehaviorSpec.js
This fixes what bugged me for a long time: The fact that we do not select newly created connections, but rather the target of the connect operation. 
As you see from the commits we were not even ready for this "fixed interaction".
----
Try it out via 
```
npx @bpmn-io/sr bpmn-io/bpmn-js#develop -l bpmn-io/diagram-js#select-connection
```
> Select connection

- assets/diagram-js.css
- lib/features/bendpoints/BendpointUtil.js
- lib/features/connect/Connect.js
- lib/features/outline/Outline.js
- lib/features/resize/ResizeHandles.js
- lib/features/selection/SelectionBehavior.js
- lib/features/selection/SelectionVisuals.js
- test/spec/features/bendpoints/BendpointsSpec.js
- test/spec/features/connect/ConnectSpec.js
- test/spec/features/resize/ResizeSpec.js
- test/spec/features/selection/SelectionBehaviorSpec.js
- test/spec/features/selection/SelectionVisualsSpec.js
This proposes a rework of our hover and select outline, as well as interaction (resize, drag, ...) handles:
* No hover state (no blinking as you move the mouse)
* Clear, solid outline for selected elements
* Clear, no opacity, unified size handles to interact with diagram elements (resize, bendpoints, ...)
Role model for this change is Google Slides, but similar approaches can be found in many different apps.
----
----
Try it out locally:
```
npx @bpmn-io/sr bpmn-io/bpmn-js#develop -l bpmn-io/diagram-js#select-hover-states
```
---
----
Related to https://github.com/bpmn-io/bpmn-js/issues/1616
> feat: clearly distinguish select and hover states

- lib/features/modeling/cmd/DeleteConnectionHandler.js
- test/spec/features/modeling/DeleteConnectionSpec.js
- test/spec/features/modeling/DeleteElementsSpec.js
related to https://github.com/bpmn-io/bpmn-js/issues/1663
> fix(modeling): remove incoming/outgoing on `connection.delete`

- assets/diagram-js.css
- lib/features/context-pad/ContextPad.js
- test/spec/features/context-pad/ContextPadProvider.js
- test/spec/features/context-pad/ContextPadSpec.js
This is to make sure that I can provide SVGs without worrying about the icon size.
> fix: limit size of context pad entry image

- lib/features/context-pad/ContextPad.js
- lib/features/palette/Palette.js
- lib/features/popup-menu/PopupMenu.js
- test/spec/features/context-pad/ContextPadSpec.js
- test/spec/features/palette/PaletteSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
Required for https://github.com/bpmn-io/bpmn-js/pull/1682
> Group popup menu items

- lib/features/popup-menu/PopupMenu.js
- test/spec/features/popup-menu/PopupMenuSpec.js
Previously, the popup menu would be stuck with `visibility: hidden`.
> fix(popup-menu): display even if no cursor is passed to `open`

- lib/util/Text.js
Related to https://github.com/bpmn-io/bpmn-js/issues/1692
> fix(util): properly assign helper-svg styles

- lib/features/editor-actions/EditorActions.js
- test/spec/features/editor-actions/EditorActionsSpec.js
Also, properly indicate copy result ("did I copy?").
----
This ensures we can use state of the art copy behavior consistently across our lib (i.e. also in cross browser copy + paste: https://github.com/nikku/bpmn-js-copy-paste-example)
> feat(editor-actions): only copy if selected elements

- assets/diagram-js.css
- lib/core/Canvas.js
- test/spec/core/CanvasSpec.js
Makes the canvas selectable by adding a `tabindex` attribute.
> Make Canvas Selectable

- package-lock.json
- package.json
- test/spec/DiagramSpec.js
Improves error reporting; previous 8.x release would use `AggregateError` which has poor inspection support across systems. That did effectively hide the cause of initialization errors.
> deps: bump to didi@8.0.1

- lib/features/keyboard/KeyboardBindings.js
- test/spec/features/keyboard/KeyboardBindingsSpec.js
The way folks in the bpmn-io sphere may now test keyboard events against common behaviors is now greatly simplified:
```javascript
import {
isUndo,
isRedo,
isPaste
} from 'diagram-js/lib/features/keyboard/KeyboardUtil';
document.addEventListener('keydown', function(event) {
if (isUndo(event)) {
// event is regarded as an UNDO event by bpmn-io tools.
}
});
```
As a breaking change we stop exporting some basic utilities in `KeyboardBindings` (exporting from actual feature modules is an anti-pattern anyway) with more to be removed in future major  upgrades. The remaining ones are continued to be used in downstream libraries (mainly form-js).
----
Non-breaking changes backported to:
* 7.x - https://github.com/bpmn-io/diagram-js/pull/663
* 8.x - https://github.com/bpmn-io/diagram-js/pull/664
> Add dedicated undo/redo keyboard utilities

- .eslintrc
- CHANGELOG.md
- karma.conf.js
- lib/command/CommandStack.js
- lib/core/Canvas.js
- package-lock.json
- package.json
* Migrated to ES2018 syntax. [Read the blog post with details and a migration guide](https://bpmn.io/blog/posts/2022-core-libraries-migrated-to-es2018.html).
---
Requires https://github.com/bpmn-io/bpmn.io/pull/147
> Use ES2018 syntax

- CHANGELOG.md
* `FIX`: consider moving and non-moving attachers when using space tool ([#480](https://github.com/bpmn-io/diagram-js/pull/480))
* `FIX`: move external labels with moving shapes/connections ([#480](https://github.com/bpmn-io/diagram-js/pull/480))
* `FIX`: allow label behavior for laid-out connections ([#480](https://github.com/bpmn-io/diagram-js/pull/480))
* label behavior for laid-out connection is not disallowed anymore
> chore(CHANGELOG): update to v10.0.0

- lib/ui/index.d.ts
- lib/ui/index.js
- package-lock.json
- package.json
- test/spec/features/bendpoints/BendpointsSpec.js
- test/spec/features/space-tool/SpaceToolSpec.js
- test/spec/ui/uiSpec.js
Exposes UI utilities through `diagram-js/lib/ui` as sketched [here](https://miro.com/app/board/uXjVPFGl7Kk=/).
> chore: provide `diagram-js/lib/ui`

- CHANGELOG.md
- lib/features/dragging/Dragging.js
- lib/features/hand-tool/HandTool.js
- lib/features/keyboard/KeyboardBindings.js
- lib/features/keyboard/KeyboardUtil.js
- lib/features/search-pad/SearchPad.js
- test/spec/features/hand-tool/HandToolSpec.js
- test/spec/features/keyboard/CopySpec.js
- test/spec/features/keyboard/KeyboardSpec.js
- test/spec/features/keyboard/PasteSpec.js
- test/spec/features/keyboard/RedoSpec.js
- test/spec/features/keyboard/UndoSpec.js
- test/spec/features/search-pad/SearchPadSpec.js
- test/util/KeyEvents.js
use KeyboardEvent.code instead
it is used to fix [camunda/camunda-modeler/2724](https://github.com/camunda/camunda-modeler/issues/2724)
I'm not sure, do you need an old check by KeyboardEvent.keyCode? Then we can use triple check
> fix: KeyboardEvent.keyCode is deprecated

- assets/diagram-js.css
- lib/features/popup-menu/PopupMenuComponent.js
- lib/features/popup-menu/PopupMenuItem.js
- lib/features/popup-menu/PopupMenuList.js
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
- test/spec/features/popup-menu/PopupMenuListSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
Closes #703 
I didn't add anything to breaking changes because it is already included with:
> HTML structure and CSS classes of the popup menu changed in the context of https://github.com/bpmn-io/diagram-js/pull/687. Ensure alignment with the new structure in your custom implementation.
> Specialize popup menu classes

- lib/features/popup-menu/PopupMenuComponent.js
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
Reverts back to the more predictable diagram-js@10 behavior.
(Naturally the popup will close anyway, i.e. through bpmn-js selection changes; otherwise it can be closed in the entry action).
Closes #702
> Do not close popup on click

- lib/features/keyboard/Keyboard.js
- test/spec/features/keyboard/KeyboardSpec.js
Ensure we play nice with other UI components up in the component tree; rather than handling keys on capture, handle events on bubble. Ignore events that got their propagation stopped or their default prevented.
A result of this PR is that components downwards in the component tree can use standard DOM facilities to prevent the event from being handled by keyboard:
```
(e)
|
* <Some Component> (e.stopPropagation())
* <Keyboard>
```
-----
Closes #707
> Make keyboard friendly enough

- lib/features/dragging/Dragging.js
- test/spec/features/dragging/DraggingSpec.js
Corrects a regression introduced with https://github.com/bpmn-io/diagram-js/pull/681/files#diff-ea53e0ed1128baaadcc175076dc701fd054fe6888b90ec144a17a786dbbca707.
> Correctly listen for <Escape> to cancel dragging

- lib/features/popup-menu/PopupMenuComponent.js
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
Depends on https://github.com/bpmn-io/diagram-js/pull/706, https://github.com/bpmn-io/diagram-js/pull/709, https://github.com/bpmn-io/diagram-js/pull/708.
----
Closes #701
> Handle keyboard input without search active

- assets/diagram-js.css
- lib/features/popup-menu/PopupMenuComponent.js
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
Testing the diagram-js@11.1.0 integration into bpmn-js I found two quirks that are worth investigating:
* We broke the semantics of the `djs-popup` class, unnecessarily => proposal to revert this via https://github.com/bpmn-io/diagram-js/commit/71f1f1c094fcb72a943c7a2fa8eb568a5487e72a
* We apply inconsistent padding / margin leading to broken UI in search/header-less popups => Fixed via https://github.com/bpmn-io/diagram-js/pull/714/commits/c28fadf21b06613a8b37ec72df104d162fa69ff3
----
> Fix upgrade issues

- lib/features/popup-menu/PopupMenu.js
- test/spec/features/popup-menu/PopupMenuSpec.js
`diagram-js@11` does not properly remove popup menu containers. As a result more and more pile up in the DOM (attached to the body).
This PR , specifically (https://github.com/bpmn-io/diagram-js/pull/715/commits/da2035a7950fee66ebcff52dab426c34f5d5ddd1) ensures that they are attached only for the time where the popup menu is actually opened.
> Fixup remove container close

- assets/diagram-js.css
- lib/features/popup-menu/PopupMenuComponent.js
- lib/features/popup-menu/PopupMenuItem.js
- lib/features/popup-menu/PopupMenuList.js
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
The origin of this PR was an investigation to upgrade the [bpmn-js-color-picker](https://github.com/bpmn-io/bpmn-js-color-picker) to use this library. That turned into [adding an actual popup menu integration test](https://github.com/bpmn-io/diagram-js/commit/474d6e330df113c377b891a7cdd6edb94bd25420) and discovering + fixing a multitude of issues:
* `FIX`: We don't account for `title` attribute in body entries; this is a regression (https://github.com/bpmn-io/diagram-js/commit/323bd88edfbde07a99b23f3bba00c9afc4ff23fb)
* `FIX`: We apply icon margins independent of whether or not the margin (between icon + X is needed). This requires us to workaround in downstream libraries (https://github.com/bpmn-io/diagram-js/commit/cf2c6651ca23153871b59e41cefb386426959f24)
* `CHORE` / `FEAT`: we don't …
> Correct various popup menu glitches

- lib/features/popup-menu/PopupMenu.js
This ensures the popup menu is not accidentally canvas scrolled on mouse wheel.
Closes https://github.com/bpmn-io/diagram-js/issues/729
> fix: prevent canvas scrolling inside popup menu

- lib/features/popup-menu/PopupMenu.js
- lib/features/popup-menu/PopupMenuComponent.js
- lib/features/popup-menu/PopupMenuItem.js
- lib/features/popup-menu/PopupMenuList.js
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
Related to https://github.com/bpmn-io/bpmn-js/pull/1802 -> https://github.com/bpmn-io/bpmn-js/pull/1802#issuecomment-1383256080
> feat(popup-menu): allow entries to be draggable

- assets/diagram-js.css
- test/spec/features/popup-menu/PopupMenuSpec.js
Related to https://github.com/bpmn-io/bpmn-js/issues/1812
> fix(popup-menu): improve set off from background

- lib/features/bendpoints/GeometricUtil.js
- lib/features/connection-preview/ConnectionPreview.js
- lib/features/outline/Outline.js
- lib/features/preview-support/PreviewSupport.js
- lib/util/Geometry.js
- lib/util/RenderUtil.js
- test/spec/features/move/MovePreviewSpec.js
- test/spec/util/RenderUtilSpec.js
Foundation for toolkits to build on top of this:
> Add ability to render connections with round corners

- lib/features/popup-menu/PopupMenuComponent.js
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
Allows integrators to assign a `rank < 0` to entries to hide them from the initial list of items. These items will appear once searched for.
Related to https://github.com/bpmn-io/bpmn-js/issues/1621
> feat(popup-menu): allow to initially hide elements

- lib/features/keyboard/KeyboardBindings.js
- lib/features/keyboard/KeyboardUtil.js
- test/spec/features/keyboard/CopySpec.js
- test/spec/features/keyboard/PasteSpec.js
- test/spec/features/keyboard/RedoSpec.js
- test/spec/features/keyboard/UndoSpec.js
This restores a the pre 11.0.0 behavior.
Related to https://github.com/bpmn-io/bpmn-js/issues/1842
> fix: remove physical keyboard bindings

- lib/util/EscapeUtil.js
- package-lock.json
- package.json
Related to https://github.com/bpmn-io/bpmn-js/issues/1850
> refactor: replace npm module `css.escape` with native API

- lib/command/CommandStack.js
This may prevent potential confusion.
> docs(command): state that `executed` hooks are also part of the transaction

- lib/i18n/translate/translate.d.ts
- lib/i18n/translate/translate.js
- lib/i18n/translate/translate.spec.ts
Translate is used quite extensively in bpmn-js, therefore I added types.
> feat: add TypeScript declarations for translate functions

- lib/features/replace/Replace.js
- lib/features/replace/ReplaceSelectionBehavior.js
- lib/features/replace/index.js
- test/spec/features/replace/ReplaceSelectionBehaviorSpec.js
- test/spec/features/replace/ReplaceSpec.js
This mirrors existing patterns (cf. auto-place).
Per default replaced elements will be selected, unless explicitly disabled via hint.
----
Idea is to get interaction related logic, where a shared concern, out of downstream libraries (properties panel [element template removal](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/663003e48cdb19942f9d7293e7269562eb8aae97/src/provider/element-templates/util/templateUtil.js#L33), [bpmn replace](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/replace/BpmnReplace.js#L290)).
> feat: support select after replacement

- lib/core/EventBus.d.ts
- lib/core/EventBus.spec.ts
Currently the type defines, that the EventCallback can only receive a single parameter `event`. However when firing an event, an arbitrary amount of additional parameters can be passed to the callback.
Closes https://github.com/bpmn-io/diagram-js/issues/758.
> Adds additional parameters to EventCallback type

- lib/features/context-pad/ContextPad.js
- lib/features/palette/Palette.js
- lib/features/popup-menu/PopupMenu.js
- test/spec/features/context-pad/ContextPadSpec.js
- test/spec/features/palette/PaletteSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
> Emit `popupMenu/palette/contextPad.trigger` events

- lib/features/bendpoints/BendpointSnapping.js
- lib/features/copy-paste/CopyPaste.js
- lib/features/create/Create.js
- lib/features/modeling/cmd/CreateElementsHandler.js
- lib/features/modeling/cmd/DeleteShapeHandler.js
- lib/features/move/MovePreview.js
- lib/features/resize/ResizeHandles.js
- lib/features/snapping/CreateMoveSnapping.js
- lib/features/snapping/ResizeSnapping.js
- lib/features/space-tool/SpaceTool.js
- lib/features/space-tool/SpaceToolPreview.js
- lib/layout/LayoutUtil.js
- lib/model/index.js
- lib/util/ModelUtil.js
- test/spec/features/copy-paste/CopyPasteSpec.js
- test/spec/model/ModelSpec.js
* export `isConnection`, `isLabel` and `isRoot` checks from `ModelUtil` and test
* use these checks
* checks will be usable by bpmn-js, too
---
Required by https://github.com/bpmn-io/bpmn-js/pull/1903
Related to https://github.com/bpmn-io/bpmn-js/issues/1901
> Centralize `isConnection`, `isLabel` and `isRoot` Checks

- README.md
No other ordering was intended in the first place.
> docs: reorder external projects alphabetically

- lib/navigation/zoomscroll/ZoomScroll.js
This PR adds support for zooming using cmd on the mac platform
It is clear that zooming with ctrl + wheel is most likely a side effect, since event.ctrlKey is also a directive for pinch zoom. but since there is a feature, why not create a more pleasant UX on Mac
> feat(zoom-scroll): add zoom by cmd + wheel on mac

- lib/features/space-tool/SpaceTool.js
- test/spec/features/space-tool/SpaceToolSpec.js
Can be tried out via `npx @bpmn-io/sr bpmn-io/bpmn-js#develop -l bpmn-io/diagram-js#local-space-tool`.
---
Related to https://github.com/bpmn-io/bpmn-js/issues/557
> feat(space-tool): add/remove space locally when pressing shift

- lib/features/outline/Outline.js
- lib/features/outline/OutlineProvider.spec.ts
- lib/features/outline/OutlineProvider.ts
- test/spec/features/outline/OutlineSpec.js
- test/spec/features/selection/SelectionVisualsSpec.js
Test with https://github.com/bpmn-io/bpmn-js/tree/updated-outlines
Related to https://github.com/bpmn-io/bpmn-js/issues/1996
> Allow custom selection outlines

- CHANGELOG.md
- lib/features/popup-menu/PopupMenuComponent.js
- lib/features/popup-menu/PopupMenuProvider.spec.ts
- lib/features/popup-menu/PopupMenuProvider.ts
- test/spec/features/popup-menu/PopupMenuSpec.js
related to https://camunda.slack.com/archives/GP70M0J6M/p1698758803858999
> feat(PopupMenu): allow `imageHtml` for header entries

- CHANGELOG.md
- lib/features/outline/Outline.js
- test/spec/features/outline/OutlineSpec.js
See reasoning [here](https://github.com/camunda/product-hub/issues/1653#issuecomment-1792114922)
> Revert: remove connection selection

- assets/diagram-js.css
Changing `djs-dragging` CSS class had unintended side effects due to class being used for other elements, too. I'll properly address this with https://github.com/bpmn-io/diagram-js/tree/fix-djs-dragging-2 but for now let's just roll back the changes.
---
Related to https://github.com/bpmn-io/bpmn-js/issues/2002
Related to https://github.com/bpmn-io/bpmn-js/issues/2010
> fix: revert `djs-dragging` CSS class changes

- lib/features/context-pad/ContextPad.js
- test/spec/features/context-pad/ContextPadProvider.js
- test/spec/features/context-pad/ContextPadSpec.js
---
Related to bpmn-io/bpmn-js#2004
> fix(context-pad): clear hover timeout on close

- assets/diagram-js.css
- lib/features/context-pad/ContextPad.js
- test/spec/features/context-pad/ContextPadSpec.js
- test/spec/features/selection/SelectionVisualsSpec.js
Related to https://github.com/camunda/product-hub/issues/1653#issuecomment-1803357533
> Connection selection outline + context pad position

- lib/features/popup-menu/PopupMenu.js
- test/spec/features/popup-menu/PopupMenuSpec.js
Related to https://github.com/camunda/improved-canvas/pull/9
Currently, we don't consider that the popup menu can open upwards. I considered doing this in the actual extension but it leads to flaky positioning. And opening downwards is a bpmn-js concern, not diagram-js. So it's fair to also consider this case imo
Before:
https://github.com/bpmn-io/diagram-js/assets/25825387/9b632855-2cd9-4f1b-bd80-2415f7e1b92e
After:
https://github.com/bpmn-io/diagram-js/assets/25825387/6b01cdac-545a-4fc5-862d-0cf552530932
> fix(popup): reposition if under axis

- lib/features/popup-menu/PopupMenuComponent.js
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
> feat(popup): allow non-searchable entries

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/workflows/CODE_SCANNING.yml
- .github/workflows/MERGE_MASTER_TO_DEVELOP.yml
- README.md
This makes `main` the default branch. To be updated in the repository once this PR receives a :heavy_check_mark:
> chore: make `main` the default branch

- package-lock.json
- package.json
This bumps to `path-intersection@3` which exposes proper module exports.
I regard this change as _non-breaking_ as diagram-js is meant to be bundled through modern module bundlers anyway.
> deps: update to path-intersection@3

- lib/features/selection/SelectionBehavior.js
- test/spec/features/selection/SelectionBehaviorSpec.js
As far as I remember, we didn't want to support Click + <kbd>CTRL</kbd> for adding to selection anyway. I was surprised to find it in the code.
---
Closes #849
> fix: remove Click + CTRL for adding to selection

- lib/features/popup-menu/PopupMenu.js
- lib/features/popup-menu/PopupMenuComponent.js
- lib/features/popup-menu/PopupMenuProvider.spec.ts
- lib/features/popup-menu/PopupMenuProvider.ts
- package-lock.json
- package.json
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
Adds `getEmptyPlaceholder` API to `PopupMenuProvider` to customize what's shown when there are no entries (after search). Based on [the original issue](https://github.com/camunda/camunda-bpmn-js/issues/322) is clear that a simple string or even an HTML string as it's used for icons (`imgHtml`) won't cut it here which means we have to allow users to return a `VNode`. The search is passed to the callback returning the `VNode` so it can be taken into account.
----
Closes https://github.com/bpmn-io/diagram-js/issues/846
> feat(popup-menu): add API to provide custom no search results entry

- README.md
Hi, @nikku
Thanks for your great work. [Apache Seata (Incubator)](https://github.com/apache/incubator-seata) is a distributed transaction framework. And recently, we have used diagram-js as the backbone to refactor our new version of Saga Designer (a visual tool to orchestrate Saga pattern transaction).
This PR aims to provide an external link in the README.
> chore: add Seata Saga designer as an external project

- lib/features/lasso-tool/LassoTool.js
- lib/util/Elements.js
- test/spec/features/lasso-tool/LassoToolSpec.js
---
Related to https://github.com/bpmn-io/bpmn-js/issues/2053
> Add to Selection When Using Lasso Tool with Shift Key

- lib/features/popup-menu/PopupMenu.js
- test/spec/features/popup-menu/PopupMenuSpec.js
Adds a `refresh` method to the popup menu. Allows updating the popup menu's entries without having to reopen it.
---
Closes #804
> feat(popup-menu): add ability to refresh without reopening

- lib/Diagram.js
- lib/Diagram.spec.ts
- lib/core/EventBus.js
- lib/core/EventBus.spec.ts
- package-lock.json
- package.json
This allows implementors to type the diagram (available services) and eventBus events (available events):
> Be able to type diagram and events

- lib/features/popup-menu/PopupMenuComponent.js
- lib/features/search-pad/SearchPad.js
- lib/features/search-pad/index.js
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
- test/spec/features/search-pad/SearchPadSpec.js
Related to https://github.com/camunda/web-modeler/issues/7930
> Add labels to inputs

- lib/features/auto-place/AutoPlace.js
- lib/features/create/Create.js
- lib/navigation/zoomscroll/ZoomScroll.js
- lib/util/Text.js
Hi,
we're in the process of upgrading from our own typedefs to the official diagram-js ones and found some cases where arguments are theoretically optional but documented as required in the jsdoc.
This PR adjusts the cases we noticed our build complaining.
The changes are usually where the argument is consumed with a fallback value in the javascript code, e.g. `argument || {}`.
If you expect these arguments not to be optional in the generated types, I can also close the PR.
Thanks
> chore: document some arguments as optional

- assets/diagram-js.css
- lib/features/keyboard/Keyboard.js
- lib/features/popup-menu/PopupMenuComponent.js
- lib/features/popup-menu/PopupMenuItem.js
- test/spec/features/keyboard/KeyboardSpec.js
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
---
This PR improves the accessibility of the popup menu:
* Ensures all items are keyboard accessible
* Ensures that existing TAB and arrow key navigation continues to work
* Ensures that `SPACE` and `ENTER` can be used as expected to toggle features
* Ensure that outside click is no longer trapped
* Use browser native outline for keyboard focus state
---
Additional notes:
* I decided that tabbing through the whole component (all entries) shall be possible
* I decided against making this a partial select/fake drop down from aria perspective, as it does not work in scenarios without search
----
Can be tried out using the following command on your local machine:
```
npx @bpmn-io/sr bpmn-io/bpmn-js -l bpmn-io/diagram-js#a11y-popup-menu
```
----
Closes #871
> A11y popup menu

- CHANGELOG.md
- lib/features/popup-menu/PopupMenuComponent.js
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
This allows us to show empty placeholder when no entries were returned (e.g. still fetching), not just when the search filters out all entries
> fix(PopupMenu): show `emptyPlaceholder` when no entries exist

- lib/core/Canvas.js
- lib/core/Canvas.spec.ts
- lib/features/context-pad/ContextPad.js
- lib/features/editor-actions/EditorActions.js
- lib/features/hand-tool/HandTool.js
- lib/features/overlays/Overlays.js
- lib/navigation/zoomscroll/ZoomScroll.js
- lib/util/Text.js
- lib/util/Types.ts
- test/spec/core/CanvasSpec.js
Hi, 
I found some additional type incompatibilities when migrating to the most recent diagram-js version.
Most of them seem to be non issues and just documenting incorrect types. Some of them were found due to intellij complaining that e.g. a switch uses a case which isn't possible according to the types.
I'm unsure if the `Canvas.spec.ts` `canvas.scroll` call previously actually tested something, because the x/y parameters weren't used anywhere in the `canvas.scroll` method.
The `setRootElement` return value is only there because the return type specifies it always returns something but in that case returned `undefined`
> chore: add some additional type corrections

- lib/features/popup-menu/PopupMenuComponent.js
This ensures the position given to the Popup menu when opening (x, y) are the real coordinates it is displayed at.
Currently, the scale origin is in the center of the container, which creates weird UI when you zoomed in to the canvas:
With the fix, the transform is applied to the corner instead:
> fix(popup-menu): keep given top-left position with scale

- CHANGELOG.md
- lib/features/context-pad/ContextPad.js
- lib/features/popup-menu/PopupMenu.js
- test/spec/features/context-pad/ContextPadSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
With this PR, the context pad and popup menu will no longer scale with the canvas zoom. To restore the old behavior, you can add the following to your configuration:
```
{
popupMenu: {
scale: {
min: 1.0,
max: 1.5
}
},
contextPad: {
scale: {
min: 1.0,
max: 1.5
}
}
}
```
closes #879
> feat(context-pad): do not scale by default

- lib/features/context-pad/ContextPad.js
- test/spec/features/context-pad/ContextPadSpec.js
Didn't break anything but would call `triggerEntry` with non-existing action. Discovered in the context of https://github.com/bpmn-io/bpmn-js/issues/2150.
> fix(context-pad): do not call `triggerEntry` twice when handling hover

- assets/diagram-js.css
- lib/features/context-pad/ContextPad.js
- test/spec/features/context-pad/ContextPadSpec.js
* context pad is not an overlay anymore
* context pad is positioned absolutely in `Canvas#getContainer()`
* context pad doesn't scale
* `ContextPad#getPad` is deprecated but will still return `{ html }` for those who need it
> feat(context-pad): position absolute intead of relative to element

- CHANGELOG.md
Prepares diagram-js with absolutely positioned context pad to be released and integrated into bpmn-js and dmn-js.
Required by https://github.com/camunda/improved-canvas/pull/61.
> chore(CHANGELOG): update to v14.5.0

- lib/features/context-pad/ContextPad.js
- test/spec/features/context-pad/ContextPadSpec.js
The fact that `elements.changed` could feature elements that were removed wasn't previously taken into account.
> fix(context-pad): do not re-open for targets that were removed

- CHANGELOG.md
* `FIX`: do not re-open context pad for elements that were removed ([#893](https://github.com/bpmn-io/diagram-js/pull/893))
> chore(CHANGELOG): update to v14.5.1

- lib/features/context-pad/ContextPad.js
- test/spec/features/context-pad/ContextPadSpec.js
Turns out I was too eager hiding the context pad. `djs-label-hidden` should not hide the context pad.
> fix(context-pad): do not hide context pad on `djs-label-hidden` added

- assets/diagram-js.css
- lib/features/popup-menu/PopupMenuComponent.js
- lib/features/popup-menu/PopupMenuHeader.js
- lib/features/popup-menu/PopupMenuProvider.spec.ts
- lib/features/popup-menu/PopupMenuProvider.ts
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
- test/spec/features/popup-menu/PopupMenuHeaderSpec.js
- test/spec/features/popup-menu/PopupMenuListSpec.js
Try out via
```
npx @bpmn-io/sr bpmn-io/bpmn-js#popup-menu-header-entry-groups-example -l bpmn-io/diagram-js#popup-menu-header-entry-groups
```
Closes #896
> feat(popup-menu): allow grouping header entries

- CHANGELOG.md
* `FEAT`: popup menu header entries can be grouped ([#900](https://github.com/bpmn-io/diagram-js/pull/900))
> chore(CHANGELOG): update to v14.6.0

- assets/diagram-js.css
- lib/features/complex-preview/ComplexPreview.js
- lib/features/preview-support/PreviewSupport.js
- test/spec/features/complex-preview/ComplexPreviewSpec.js
- test/spec/features/preview-support/renderer/MarkerRenderer.js
This PR
- Adds support for non-root `def` sections in the svg
- Moves the copied svg markers into the preview visuals. This makes cleanup easier and more consistent.
closes #904
Test it out with 
```
npx @bpmn-io/sr bpmn-io/bpmn-js#marker-rework -l bpmn-io/diagram-js#904-marker-rework
```
downstream draft PR: https://github.com/bpmn-io/bpmn-js/pull/2173
> feat(preview-support): add copied marker as part of djs-visual

- CHANGELOG.md
- lib/features/move/MovePreview.js
- lib/features/preview-support/PreviewSupport.js
- test/spec/features/complex-preview/ComplexPreviewSpec.js
- test/spec/features/move/MovePreviewSpec.js
- test/spec/features/preview-support/nested-renderer/MarkerRenderer.js
- test/spec/features/preview-support/nested-renderer/index.js
This PR:
- changes the marker ID if it was part of the `djs-visual` instead of creating a new one.
- Adds a random string to the copied marker ID. This ensures we do not have overlaps if the same connection is present multiple times in a preview. While this should not happen, it did happen in the past so better be safe here.
- Ensures we copy connections only once in move preview
related to https://github.com/bpmn-io/bpmn-js/issues/2179
> Prevent duplicate marker ids in preview

- package-lock.json
- package.json
Improves [`clear`](https://github.com/bpmn-io/tiny-svg/blob/main/lib/clear.js).
> deps: bump to tiny-svg@3.1.2 / min-dom@4.2.1

- lib/features/context-pad/ContextPad.js
- test/spec/features/context-pad/ContextPadSpec.js
I investigated https://camunda-modeling.sentry.io/share/issue/d4edab8eb6044c74b7c933158b06a69a/ which happens when reacting to `element.marker.update` which calls `canvas.hasMarker` for each of the current targets. In some cases that I couldn't reproduce it seems like at least one of the targets has been deleted at the time of calling `canvas.hasMarker` which leads to a `A DOM element reference is required` since there is no graphical element anymore. While I couldn't reproduce the issue I changed the implementation so context pad visibility is updated on `element.marker.update` only if the element is a target. This might or might not fix the issue. We'll have to keep an eye on the Sentry issue.
> Do not update context pad visibility on `element.marker.update` if element is not target

- CHANGELOG.md
- lib/core/Canvas.js
As implemented by @marstamm and discussed in https://github.com/bpmn-io/diagram-js/pull/915#issuecomment-2183924816 we want marker querying to not be a DOM operation (costly).
Related to https://github.com/camunda/camunda-modeler/issues/4335
> Do not query DOM for `Canvas#hasMarker` check

- CHANGELOG.md
- lib/features/context-pad/ContextPad.js
- lib/features/context-pad/index.js
- lib/features/scheduler/Scheduler.js
- lib/features/scheduler/index.js
- test/spec/features/context-pad/ContextPadSpec.js
- test/spec/features/scheduler/SchedulerSpec.js
Significantly improves deselection performance
related to https://github.com/camunda/camunda-modeler/issues/4335
> fix(context-pad): only update visibility once per frame

- lib/features/context-pad/ContextPad.js
As shown in this flame graph, in a huge diagram, we spend substantial amount of time to re-compute canvas viewport (after select) and determine context pad position (to update it):
All this happens within the user transaction, and blocks UI interactivity.
With this PR we batch position updates as we batch visibility updates; we'll otherwise force the browser into expensive in-frame repaints:
Related to https://github.com/bpmn-io/diagram-js/pull/915, https://github.com/camunda/camunda-modeler/issues/4335.
> chore(context-pad): update position once per frame

- lib/command/CommandHandler.ts
- lib/draw/DefaultRenderer.spec.ts
- lib/features/context-pad/ContextPadProvider.ts
- lib/features/outline/OutlineProvider.ts
- lib/features/popup-menu/PopupMenuProvider.ts
- lib/features/search-pad/SearchPadProvider.ts
Fixes #864 by changing `import { ... } from` to `import type { ... } from` in the typescript files at all locations where types are imported. This will make this package compatible with projects using the verbatimModuleSyntax flag in the tsconfig.
This is not a breaking change.
> chore: add "type" symbol to typescript imports to make package compatible with 'verbatimModuleSyntax'

- assets/diagram-js.css
- lib/features/search-pad/SearchPad.js
- lib/features/search-pad/SearchPadProvider.ts
- test/spec/features/search-pad/SearchPadSpec.js
Improves search by
* treating search as truly intermediate (root element, selection and viewbox reset on escape without click or enter)
* aligning styles with other popups
* simplifying selection visuals when "pre-selecting" elements before selecting (click or enter)
* simply use existing outline
* don't show context pad during pre-select
Related to https://github.com/bpmn-io/bpmn-js/pull/2187
> Search improvements

- lib/features/search-pad/SearchPad.js
- test/spec/features/search-pad/SearchPadSpec.js
* prevents resetting view when clicking outside of search (cf. https://github.com/bpmn-io/bpmn-js/pull/2187#issuecomment-2303198593)
* reduces padding for scrolling into view
> Search fixes

- lib/features/popup-menu/PopupMenu.js
- lib/features/popup-menu/PopupMenuComponent.js
- lib/features/popup-menu/index.js
- lib/features/search/index.js
- lib/features/search/search.js
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
- test/spec/features/search/searchSpec.js
* adds ability for popup menu providers to provide custom search
* default search sorts matches by location (when searching for "foo", "foo bar" will appear before "bar foo")
> Popup menu search

- CHANGELOG.md
- lib/features/popup-menu/PopupMenu.js
- lib/features/popup-menu/PopupMenuComponent.js
- lib/features/popup-menu/index.js
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
This reverts the integration of the (partially broken) search into the popup menu.
The feature needs further refinement, cf. https://github.com/bpmn-io/diagram-js/pull/932, https://github.com/bpmn-io/diagram-js/pull/932#issuecomment-2368956271.
> chore: unbuild search integration in popup menu

- assets/diagram-js.css
- lib/core/Canvas.js
- lib/features/search-pad/SearchPad.js
- test/spec/core/CanvasSpec.js
- test/spec/features/search-pad/SearchPadSpec.js
* do not set zoom to 1
* reduce padding below search
* add custom marker to preselected element
Related to https://github.com/bpmn-io/bpmn-js/issues/2233
Related to https://github.com/camunda/camunda-modeler/issues/4538
> Improve search in large diagrams

- lib/core/Canvas.js
- test/spec/core/CanvasSpec.js
Uses `structuredClone` to clone viewbox and simplifies test.
Previously code like [this](https://github.com/bpmn-io/diagram-js/blob/develop/lib/core/Canvas.js#L1284) would get a reference to `_cachedViewbox` and then modify it.
Follow-up to https://github.com/bpmn-io/diagram-js/pull/931
> chore: simplify viewbox cloning

- CHANGELOG.md
- lib/features/outline/MultiSelectionOutline.js
- lib/features/outline/index.js
- lib/features/selection/SelectionVisuals.js
- lib/features/selection/index.js
- test/spec/features/outline/MultiSelectionOutlineSpec.js
- test/spec/features/outline/OutlineSpec.js
- test/spec/features/selection/SelectionBehaviorSpec.js
- test/spec/features/selection/SelectionVisualsSpec.js
This PR moves multi selection outline logic from `selection` to `outline`. As a result selection is a non-UI component, and outline builds (optionally) on top of it.
Closes #944 
> Move multi selection outline into separate feature

- CHANGELOG.md
- lib/core/Canvas.js
- lib/features/keyboard/Keyboard.js
- lib/features/popup-menu/PopupMenu.js
- lib/features/search-pad/SearchPad.js
- test/spec/core/CanvasSpec.js
- test/spec/features/keyboard/KeyboardSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
- test/spec/features/search-pad/SearchPadSpec.js
Keyboard is not implicitly bound and `Canvas` is a focusable element.
This builds foundations to [support cross-browser/application copy and paste](https://github.com/bpmn-io/internal-docs/issues/614) and more general keyboard related UX enhancements.
This change introduces a predictable editing experience, simplifies the keyboard and ensures worry free interoperability with multiple editors and inputs on the page.
Keyboard is now implicitly bound to the canvas element (svg). It provides behavior closer to native browser experience.
Previous calls to `keyboard.bind(someElement)` or configuration via `keyboard.bindTo` log a descriptive descriptive error:
The `Canvas` is now a focusable component, that is recognized accordingly by the browser, with all benefits for UX and interaction. New …
> Make canvas selectable / keyboard binding implicit

- lib/features/popup-menu/PopupMenu.js
- lib/features/popup-menu/PopupMenuComponent.js
- lib/features/popup-menu/index.js
- lib/features/search-pad/SearchPad.js
- lib/features/search-pad/SearchPadProvider.ts
- lib/features/search-pad/SearchProvider.spec.ts
- lib/features/search/search.js
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
- test/spec/features/popup-menu/PopupMenuSpec.js
- test/spec/features/search-pad/SearchPadSpec.js
- test/spec/features/search/searchSpec.js
We found various issues with our existing search, both in terms of robustness and behavior:
* Under certain circumstances searching loops infinitely (https://github.com/camunda/web-modeler/pull/10940)
* Search is no longer fuzzy, i.e. matches terms across all fields, and hence is overly strict (https://github.com/bpmn-io/diagram-js/pull/932#issuecomment-2368956271)
* Search does not return _all_ tokens for matched entries, making it hard to integrate it properly (https://github.com/bpmn-io/bpmn-js/pull/2235)
* Lack of test coverage around contract and other crucial aspects
This PR solves these issues, while keeping the generally desirable properties:
* We sort search results semantically, preferring
* start of word
* start of term (in word)
* we sort alphabetically (where items are equal …
> Improve search (make fuzzy again and more robust)

- assets/diagram-js.css
- lib/features/search-pad/SearchPad.js
- test/spec/features/search-pad/SearchPadSpec.js
I traced a bug that caused the `preselect` marker class not being removed from an element. In the process I found that the whole marker logic we introduced via https://github.com/bpmn-io/diagram-js/pull/913 is _not_ necessary, after all: We use standard selection, and attach a `djs-search-open` marker to the diagram container; this is enough for us to handle "special selection" using plain CSS:
_The change in action, testing against [bpmn-js](https://github.com/bpmn-io/bpmn-js)._
> Simplify search pad preselect

- lib/features/keyboard/Keyboard.js
- lib/features/keyboard/Keyboard.spec.ts
In a previous update the ability to bind the keyboard to a specific node has been removed. The current JS-doc resulted in a generated type definition still requiring an `EventTarget` as parameter for the `bind` method even though supplying this parameter leads to an error and has no effect.
Prior (generated `Keyboard.d.ts`):
```
/**
* Bind keyboard events to the given DOM node.
*
* @param node
*/
bind(node: EventTarget): void;
```
After:
```
/**
* Bind keyboard events to the given DOM node.
*
* @param node
*/
bind(node: undefined): void;
```
---
Related to https://github.com/bpmn-io/diagram-js/pull/662
> fix(keyboard): bind-method typing still requires EventTarget

- lib/features/popup-menu/PopupMenuComponent.js
- lib/features/search-pad/SearchPad.js
- lib/features/search/search.js
- test/spec/features/popup-menu/PopupMenuSpec.js
- test/spec/features/search-pad/SearchPadSpec.js
- test/spec/features/search/searchSpec.js
This ensures that search only handles non-empty search queries, components integrating with it need to ensure that non-empty search is provided:
_Whitespace only ignored by global search:_
_Whitespace only ignored by popup menu search:_
Related to https://github.com/camunda/camunda-modeler/pull/4711#issuecomment-2491044304
> Handle empty search queries (ignore it)

- CHANGELOG.md
- lib/features/search/search.js
- test/spec/features/search/searchSpec.js
Test via `npx @bpmn-io/sr bpmn-io/bpmn-js -l bpmn-io/diagram-js#search-start`
This prioritizes start of term and exact matches more aggressively.
_This yields more substantial results in large popup (append) menus:_
_This yields better search results when querying larger data pools, where exact matches would otherwise de-prioritized:_
Related to https://github.com/camunda/camunda-modeler/issues/4122, https://github.com/camunda/camunda-modeler/issues/3439.
> fix(search): prioritize start of word and exact match more

- test/spec/features/popup-menu/PopupMenuSpec.js
On systems with high resolution screens, one test fails as it is of by a slightly higher number the higher the screen resolution is. This is a hotfix to accomodate more screen sizes. Other suggestions to fix this test are welcome.
> Increase closeBy position to accommodate higher screen resolutions

- lib/features/popup-menu/PopupMenuComponent.js
- lib/features/popup-menu/PopupMenuList.js
- lib/features/popup-menu/PopupMenuProvider.ts
- test/spec/features/popup-menu/PopupMenuComponentSpec.js
- test/spec/features/popup-menu/PopupMenuHeaderSpec.js
- test/spec/features/popup-menu/PopupMenuListSpec.js
Related to https://github.com/bpmn-io/bpmn-js-create-append-anything/issues/53
Ensure we use the post-grouping order when navigating the popup menu by keyboard.
[Screencast from 2025-09-19 10-48-42.webm](https://github.com/user-attachments/assets/d1cfd80c-08c9-4caf-9544-6e4e063f5ebb)
Ignore the disabled entries it's from another PR. 
To try it out:
```
npx @bpmn-io/sr bpmn-io/bpmn-js-element-templates -l bpmn-io/diagram-js#cr-app-an-53-match-keyboard-nav-to-visual-order
```
> fix: ensure keyboard entries navigation accounts for group order
